package xpath3_test

import (
	"strings"
	"testing"

	"github.com/lestrrat-go/helium/xpath3"
	"github.com/stretchr/testify/require"
)

// TestDurationAccessorsExactSeconds verifies the *-from-duration accessors use
// the exact SecRat-aware seconds magnitude rather than the lossy float64
// Seconds field, so a fraction arbitrarily close to a whole second does not
// inflate the whole-second part.
func TestDurationAccessorsExactSeconds(t *testing.T) {
	doc := mustParseXML(t, "<root/>")

	tests := []struct {
		name string
		expr string
		want string
	}{
		{
			name: "seconds near-one fraction stays sub-second",
			expr: `seconds-from-duration(xs:dayTimeDuration("PT0.9999999999999999999S"))`,
			want: "0.9999999999999999999",
		},
		{
			name: "days from large duration",
			expr: `days-from-duration(xs:dayTimeDuration("P3DT4H5M6S"))`,
			want: "3",
		},
		{
			name: "hours from large duration",
			expr: `hours-from-duration(xs:dayTimeDuration("P3DT4H5M6S"))`,
			want: "4",
		},
		{
			name: "minutes from large duration",
			expr: `minutes-from-duration(xs:dayTimeDuration("P3DT4H5M6S"))`,
			want: "5",
		},
		{
			name: "seconds whole with fraction",
			expr: `seconds-from-duration(xs:dayTimeDuration("P3DT4H5M6.5S"))`,
			want: "6.5",
		},
		{
			name: "days negative",
			expr: `days-from-duration(xs:dayTimeDuration("-P3DT4H5M6S"))`,
			want: "-3",
		},
		{
			name: "hours negative",
			expr: `hours-from-duration(xs:dayTimeDuration("-P3DT4H5M6S"))`,
			want: "-4",
		},
		{
			name: "minutes negative",
			expr: `minutes-from-duration(xs:dayTimeDuration("-P3DT4H5M6S"))`,
			want: "-5",
		},
		{
			name: "seconds negative fractional",
			expr: `seconds-from-duration(xs:dayTimeDuration("-PT6.5S"))`,
			want: "-6.5",
		},
		{
			name: "seconds modulo 60",
			expr: `seconds-from-duration(xs:dayTimeDuration("PT125S"))`,
			want: "5",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			seq := evalExpr(t, doc, tt.expr)
			require.Equal(t, 1, seq.Len())
			av := seq.Get(0).(xpath3.AtomicValue)
			got, err := xpath3.AtomicToString(av)
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

// TestDateTimePlusExactDayTimeDuration verifies date/time ± dayTimeDuration uses
// the exact SecRat seconds, so a fractional duration just below a whole second
// does not round the result up to the next second.
func TestDateTimePlusExactDayTimeDuration(t *testing.T) {
	doc := mustParseXML(t, "<root/>")

	tests := []struct {
		name string
		expr string
		want string
	}{
		{
			name: "time plus near-one fraction stays sub-second",
			expr: `xs:time("00:00:00") + xs:dayTimeDuration("PT0.9999999999999999999S")`,
			want: "00:00:00.999999999",
		},
		{
			name: "dateTime plus whole days",
			expr: `xs:dateTime("2020-01-01T00:00:00") + xs:dayTimeDuration("P5D")`,
			want: "2020-01-06T00:00:00",
		},
		{
			name: "dateTime minus whole days",
			expr: `xs:dateTime("2020-01-06T00:00:00") - xs:dayTimeDuration("P5D")`,
			want: "2020-01-01T00:00:00",
		},
		{
			name: "time minus fractional second",
			expr: `xs:time("00:00:01") - xs:dayTimeDuration("PT0.5S")`,
			want: "00:00:00.5",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			seq := evalExpr(t, doc, tt.expr)
			require.Equal(t, 1, seq.Len())
			av := seq.Get(0).(xpath3.AtomicValue)
			got, err := xpath3.AtomicToString(av)
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

// TestYearMonthDurationRejectsUnderflowingDayTime verifies that an
// underflowing-but-nonzero EXACT dayTime seconds value is rejected when casting
// to xs:yearMonthDuration, rather than being silently accepted as P0M.
func TestYearMonthDurationRejectsUnderflowingDayTime(t *testing.T) {
	lex := "PT0." + strings.Repeat("0", 400) + "1S"
	_, err := xpath3.CastFromString(lex, xpath3.TypeYearMonthDuration)
	require.Error(t, err)

	// A genuine yearMonth-only lexical form still casts cleanly.
	av, err := xpath3.CastFromString("P2Y3M", xpath3.TypeYearMonthDuration)
	require.NoError(t, err)
	got, err := xpath3.AtomicToString(av)
	require.NoError(t, err)
	require.Equal(t, "P2Y3M", got)
}

// TestNonTerminatingFractionTruncated verifies that a capped non-terminating
// fraction is generated by TRUNCATING long division (never rounding), so the
// integer part can never carry into an invalid "PT0.1.S".
func TestNonTerminatingFractionTruncated(t *testing.T) {
	doc := mustParseXML(t, "<root/>")

	// 1 div 9 second = 0.111... (non-terminating). 1 minus that approaches a
	// whole second; the truncating formatter must keep the integer part at 0.
	seq := evalExpr(t, doc, `xs:dayTimeDuration("PT1S") - (xs:dayTimeDuration("PT1S") div 9)`)
	require.Equal(t, 1, seq.Len())
	av := seq.Get(0).(xpath3.AtomicValue)
	got, err := xpath3.AtomicToString(av)
	require.NoError(t, err)
	// 8/9 = 0.888... truncated to 40 digits, no carry, no stray decimal point.
	require.Equal(t, "PT0."+strings.Repeat("8", 40)+"S", got)
	require.NotContains(t, got, "1.")
	require.Equal(t, 1, strings.Count(got, "."))
}
