// Code generated by tools/qt3gen; DO NOT EDIT.

package xpath3_test

import "testing"

func TestQT3_misc_AppendixA4(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "appendix-A4-1", XPath: "-3 + 5 * 3", Assertions: []qt3Assertion{qt3AssertEq("12")}},
		{Name: "appendix-A4-2", XPath: "3 - 5 * 3", Assertions: []qt3Assertion{qt3AssertEq("-12")}},
		{Name: "appendix-A4-3", XPath: "3 + 10 div 2", Assertions: []qt3Assertion{qt3AssertEq("8")}},
		{Name: "appendix-A4-4", XPath: "5 - 10 div 2", Assertions: []qt3Assertion{qt3AssertEq("0")}},
		{Name: "appendix-A4-5", XPath: "5 + 10 idiv 4", Assertions: []qt3Assertion{qt3AssertEq("7")}},
		{Name: "appendix-A4-6", XPath: "5 - 10 idiv 4", Assertions: []qt3Assertion{qt3AssertEq("3")}},
		{Name: "appendix-A4-7", XPath: "5 + 10 mod 4", Assertions: []qt3Assertion{qt3AssertEq("7")}},
		{Name: "appendix-A4-8", XPath: "5 - 10 mod 4", Assertions: []qt3Assertion{qt3AssertEq("3")}},
		{Name: "appendix-A4-9", XPath: "-+7", Assertions: []qt3Assertion{qt3AssertEq("-7")}},
	})
}

func TestQT3_misc_ErrorsAndOptimization(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "errors-and-optimization-1", XPath: "if (true()) then 1 else error(QName('http://www.example.com/errors', 'err:oops'), \"Oops, this error should not be raised!\")", Assertions: []qt3Assertion{qt3AssertEq("1")}},
		{Name: "errors-and-optimization-2", XPath: "if (true()) then 1 div 0 else 1", ExpectError: true},
		{Name: "errors-and-optimization-4", XPath: "string-length((\"one\", \"two\"))", ExpectError: true},
		{Name: "errors-and-optimization-5", XPath: "let $e := (1,2) return $e eq 0", ExpectError: true},
		{Name: "errors-and-optimization-6", XPath: "for $s in \"var:QName\" return QName($s)", ExpectError: true},
		{Name: "errors-and-optimization-7", XPath: "if (true()) then 1 else let $unbound:var := 2 return $unbound:var", ExpectError: true},
	})
}

func TestQT3_misc_HigherOrderFunctions(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "hof-005", XPath: "let $f := concat#8 return $f('a','b','c','d','e','f','g','h')", Assertions: []qt3Assertion{qt3AssertStringValue("abcdefgh")}},
		{Name: "hof-008", XPath: "let $f := xs:date#1 return $f('2008-01-31')", Assertions: []qt3Assertion{qt3AssertStringValue("2008-01-31")}},
		{Name: "hof-023", XPath: `let $f := fn:function-name#1, $n := function-name($f) 
        return (local-name-from-QName($n), namespace-uri-from-QName($n), function-arity($f))`, Assertions: []qt3Assertion{qt3AssertStringValue("function-name http://www.w3.org/2005/xpath-functions 1")}},
		{Name: "hof-024", XPath: `let $f := xs:dateTime#1, $n := function-name($f) 
        return (local-name-from-QName($n), namespace-uri-from-QName($n), function-arity($f))`, Assertions: []qt3Assertion{qt3AssertStringValue("dateTime http://www.w3.org/2001/XMLSchema 1")}},
		{Name: "hof-025", XPath: `let $f := concat#123456, $n := function-name($f) 
        return (local-name-from-QName($n), namespace-uri-from-QName($n), function-arity($f))`, Assertions: []qt3Assertion{qt3AssertStringValue("concat http://www.w3.org/2005/xpath-functions 123456")}},
		{Name: "hof-027", XPath: `let $f := fn:contains(?, "e") 
        return for $s in ("Mike", "John", "Dave", "Mary", "Jane") return $f($s)`, Assertions: []qt3Assertion{qt3AssertStringValue("true false true false true")}},
		{Name: "hof-032", XPath: "(if (current-date() gt xs:date('2000-12-31')) then upper-case#1 else lower-case#1)(\"Mike\")", Assertions: []qt3Assertion{qt3AssertStringValue("MIKE")}},
		{Name: "hof-033", XPath: "local-name-from-QName(function-name((upper-case#1, lower-case#1)[.(\"Mike\") = \"MIKE\"]))", Assertions: []qt3Assertion{qt3AssertStringValue("upper-case")}},
		{Name: "hof-916", XPath: "let $ops := substring-before(?, ?) return $ops('Michael Kay')", ExpectError: true},
		{Name: "hof-917", XPath: "let $ops := substring-before(?, 2) return $ops('Michael Kay')", ExpectError: true},
		{Name: "function-item-1", XPath: "concat#64 instance of function(*)", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "function-item-2", XPath: "string-join#1((\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\", \"i\", \"j\"))", Assertions: []qt3Assertion{qt3AssertStringValue("abcdefghij")}},
		{Name: "function-item-3", XPath: "string-join#1 is string-join#1", ExpectError: true},
		{Name: "function-item-4", XPath: "string-join#1 eq string-join#1", ExpectError: true},
		{Name: "function-item-7", XPath: "(let $a := 92, $b := true() return function($c) { $a, $b, $c })(\"lala\")", Assertions: []qt3Assertion{qt3AssertDeepEq("92, true(), \"lala\"")}},
		{Name: "function-item-8", XPath: "function-name(function-name#1)", Assertions: []qt3Assertion{qt3AssertEq("xs:QName(\"fn:function-name\")")}},
		{Name: "function-item-9", XPath: "function-name(let $a := 92, $b := true() return function($c) { $a, $b, $c })", Assertions: []qt3Assertion{qt3AssertCount(0)}},
		{Name: "function-item-10", XPath: "(let $a := 92, $b := true() return function($c) { $a, $b, $c }) instance of function(item()*) as item()*", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "function-item-11", XPath: "(let $a := 92, $b := true() return function($c) { $a, $b, $c })((xs:QName(\"foo\"), 5.0e3))", Assertions: []qt3Assertion{qt3AssertDeepEq("92, true(), fn:QName(\"\",\"foo\"), 5000")}},
		{Name: "function-item-12", XPath: "function($a as item()) as item() { $a } instance of function(*)", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "function-item-13", XPath: "function($a as item()) as xs:integer { $a } instance of function(item()) as item()", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "function-item-14", XPath: "function($a as item()) as item() { $a } instance of function(xs:string) as item()", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "function-item-15", XPath: "function($a as item()) as item() { $a } instance of function() as item()", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "function-item-16", XPath: "function($a as item()) as xs:integer { $a } instance of function(item(), item()) as item()", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "function-item-17", XPath: "function($a as xs:string) as item() { $a } instance of function(item()) as item()", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "inline-function-1", XPath: "function() { 5 } instance of function(*)", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "inline-function-2", XPath: "function-name(function() { 5 })", Assertions: []qt3Assertion{qt3AssertCount(0)}},
		{Name: "inline-function-3", XPath: "function() as xs:integer { 5 }()", Assertions: []qt3Assertion{qt3AssertEq("5")}},
		{Name: "inline-function-4", XPath: "function($a as xs:integer) as xs:integer { $a + 5 }(3)", Assertions: []qt3Assertion{qt3AssertEq("8")}},
		{Name: "inline-function-5", XPath: "function($a as xs:integer, $b as xs:double) as xs:double { $a * $b + 5 }(3, 2)", Assertions: []qt3Assertion{qt3AssertEq("11")}},
		{Name: "inline-function-6", XPath: "function($a, $b as xs:double) as xs:double { $a * $b + 5 } instance of function(item()*, xs:double) as xs:double", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "inline-function-7", XPath: "function($a as node()+, $b) as xs:double { $a * $b + 5 } instance of function(node(), item()*) as xs:double", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "inline-function-8", XPath: "function($a as node()+) { $a + 5 } instance of function(node()) as item()*", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "inline-function-9", XPath: "function() { true() } instance of function() as item()*", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "inline-function-10", XPath: "function($a) { \"lala\", $a }, $a", ExpectError: true},
		{Name: "inline-function-11", XPath: "let $a := \"monkey\" return function($a) { \"lala\", $a }(\"gibbon\")", Assertions: []qt3Assertion{qt3AssertDeepEq("\"lala\", \"gibbon\"")}},
		{Name: "inline-function-12", XPath: "$a, function($a) { \"lala\", $a }", ExpectError: true},
		{Name: "inline-function-11a", XPath: "function($a) { let $a := \"monkey\" return (\"lala\", $a) }(\"gibbon\")", Assertions: []qt3Assertion{qt3AssertDeepEq("\"lala\", \"monkey\"")}},
		{Name: "inline-function-12a", XPath: "function($a, $a) { \"lala\", $a }(\"gibbon\", \"monkey\")", ExpectError: true},
		{Name: "inline-function-15", XPath: `function($Q{http://local/}foo, $Q{http://local/}bar, $Q{http://local/}foo) { 
              "lala", $Q{http://local/}foo, $Q{http://local/}bar }("gibbon", "monkey", "ape")`, ExpectError: true},
		{Name: "inline-function-16", XPath: `function($Q{http://local/}foo, $Q{http://local/}bar, $fn:foo) { 
               "lala", $Q{http://local/}foo, $Q{http://local/}bar }("gibbon", "monkey", "ape")`, Assertions: []qt3Assertion{qt3AssertDeepEq("\"lala\", \"gibbon\", \"monkey\"")}},
		{Name: "xqhof5", XPath: `let $a := string-join(?, "")
         return $a(("foo", "bar", "baz"))`, Assertions: []qt3Assertion{qt3AssertEq("\"foobarbaz\"")}},
		{Name: "xqhof7", XPath: "concat#3(\"one\", \"two\")", ExpectError: true},
		{Name: "xqhof8", XPath: "concat#4(\"one\", ?, \"three\")", ExpectError: true},
		{Name: "xqhof9", XPath: "concat#2(\"one\", ?, \"three\")", ExpectError: true},
		{Name: "xqhof10", XPath: `for $f in (concat("one ", ?, " three"), substring-before("one two three", ?), matches(?, "t.*o"), xs:NCName(?))
         return $f("two")`, Assertions: []qt3Assertion{qt3AssertDeepEq("\"one two three\", \"one \", true(), xs:NCName(\"two\")")}},
		{Name: "xqhof11", XPath: "()(\"two\")", ExpectError: true},
		{Name: "xqhof12", XPath: "(concat(\"one \", ?, \" three\"), substring-before(\"one two three\", ?), matches(?, \"t.*o\"), xs:NCName(?))(\"two\")", ExpectError: true},
	})
}

func TestQT3_misc_Surrogates(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "surrogates08", XPath: "codepoints-to-string((97, 98, 99, 119126, 100, 101, 102))", Assertions: []qt3Assertion{qt3AssertStringValue("abc𝅖def")}},
		{Name: "surrogates01a", XPath: "string-length(\"abc𝅖def\")", Assertions: []qt3Assertion{qt3AssertEq("7")}},
		{Name: "surrogates02a", XPath: "substring(\"abc𝅖def\", 5)", Assertions: []qt3Assertion{qt3AssertStringValue("def")}},
		{Name: "surrogates03a", XPath: "substring(\"abc𝅖def\", 4)", Assertions: []qt3Assertion{qt3AssertStringValue("𝅖def")}},
		{Name: "surrogates04a", XPath: "translate(\"abc𝅖def\", \"𝅖\", \"#\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc#def")}},
		{Name: "surrogates05a", XPath: "translate(\"abc𝅖def\", \"𝅖de\", \"#DE\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc#DEf")}},
		{Name: "surrogates06a", XPath: "translate(\"abc𝅖def\", \"def\", \"𝅖EF\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc𝅖𝅖EF")}},
		{Name: "surrogates07a", XPath: "string-to-codepoints(\"abc𝅖def\")", Assertions: []qt3Assertion{qt3AssertStringValue("97 98 99 119126 100 101 102")}},
		{Name: "surrogates08a", XPath: "codepoints-to-string((97, 98, 99, 119126, 100, 101, 102))", Assertions: []qt3Assertion{qt3AssertStringValue("abc𝅖def")}},
		{Name: "surrogates09a", XPath: "substring-before(\"abc𝅖def\", \"𝅖\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc")}},
		{Name: "surrogates10a", XPath: "substring-before(\"abc𝅖def\", \"f\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc𝅖de")}},
		{Name: "surrogates11a", XPath: "substring-after(\"abc𝅖def\", \"𝅖\")", Assertions: []qt3Assertion{qt3AssertStringValue("def")}},
		{Name: "surrogates12a", XPath: "matches(\"abc𝅗def\", \"abc[𝅖-𝅘]def\")", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "surrogates13a", XPath: "matches(\"abc𝅗def\", \"abc.def\")", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "surrogates14a", XPath: "replace(\"abc𝅚def\", \"[𝅐-𝅘𝅥]\", \"𝅘𝅥\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc𝅘𝅥def")}},
		{Name: "surrogates15a", XPath: "replace(\"abc𝅗def\", \"[^a-f]\", \"###\")", Assertions: []qt3Assertion{qt3AssertStringValue("abc###def")}},
		{Name: "surrogates16a", XPath: "string-to-codepoints(substring(\"\U0010fc00A\", 2, 1))", Assertions: []qt3Assertion{qt3AssertEq("65")}},
	})
}

func TestQT3_misc_UCACollation(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "UCA-collation-001", XPath: "compare('abc','aBC',concat($collation,'fallback=unknown'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"), qt3CheckEq("-1"), qt3CheckEq("1"))}},
		{Name: "UCA-collation-002", XPath: "compare('abc','aBC',concat($collation,'fallback=no;keyword=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-003", XPath: "compare('abc','aBC',concat($collation,'fallback=no;strength=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-004", XPath: "compare('abc','aBC',concat($collation,'fallback=no;alternate=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-005", XPath: "compare('abc','aBC',concat($collation,'fallback=no;backwards=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-006", XPath: "compare('abc','aBC',concat($collation,'fallback=no;normalization=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-007", XPath: "compare('abc','aBC',concat($collation,'fallback=no;caseLevel=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-008", XPath: "compare('abc','aBC',concat($collation,'fallback=no;caseFirst=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-010", XPath: "compare('abc','aBC',concat($collation,'fallback=no;numeric=unknown'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-collation-011", XPath: "compare('abc','def',concat($collation,'keyword=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-012", XPath: "compare('abc','def',concat($collation,'strength=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-013", XPath: "compare('abc','def',concat($collation,'alternate=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-014", XPath: "compare('abc','def',concat($collation,'backwards=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-015", XPath: "compare('abc','def',concat($collation,'normalization=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-016", XPath: "compare('abc','def',concat($collation,'caseLevel=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-017", XPath: "compare('abc','def',concat($collation,'caseFirst=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-018", XPath: "compare('abc','def',concat($collation,'hiraganaQuaternary=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-019", XPath: "compare('abc','def',concat($collation,'numeric=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-020", XPath: "compare('abc','def',concat($collation,'version=5.0'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-021", XPath: "compare('abc','def',concat($collation,'version=6.0'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-022", XPath: "compare('abc','xyz',concat($collation,'version=7.0'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-022a", XPath: "compare('abc','xyz',concat($collation,'version=1.255'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-023", XPath: "compare('abc','xyz',concat($collation,'version=unknown'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-collation-024", XPath: "compare('abc','aBC',concat($collation,'version=96.5;fallback=no'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-reorder-codes-001", XPath: "compare('.123','123',concat($collation,'fallback=no;reorder=Z,digit'))", Skip: "requires external parameters", ExpectError: true},
		{Name: "UCA-reorder-codes-002", XPath: "compare('ab123','ab456',concat($collation,'reorder=Z,digit'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-reorder-codes-003", XPath: "compare('ab123','ab456',concat($collation,'fallback=yes;reorder=Z,digit'))", Skip: "requires external parameters", Assertions: []qt3Assertion{qt3AssertEq("-1")}},
		{Name: "UCA-reorder-codes-004", XPath: "compare('.123','123',concat($collation,'reorder=punct,digit;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-reorder-codes-005", XPath: "compare('.123','123',concat($collation,'reorder=digit,punct;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-reorder-codes-006", XPath: "compare(' 123','123',concat($collation,'reorder=space,digit;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-reorder-codes-007", XPath: "compare(' 123','123',concat($collation,'reorder=digit,space;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-reorder-codes-008", XPath: "compare('£123','123',concat($collation,'reorder=currency,digit;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-reorder-codes-009", XPath: "compare('£123','123',concat($collation,'reorder=digit,currency;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-reorder-codes-010", XPath: "compare('a123','123',concat($collation,'reorder=Latn,digit;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-reorder-codes-011", XPath: "compare('a123','123',concat($collation,'reorder=digit,Latn;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-001", XPath: "compare('abc','aBC',concat($collation,'strength=primary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-002", XPath: "compare('abc','aBC',concat($collation,'strength=secondary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-003", XPath: "compare('abc','aBC',concat($collation,'strength=tertiary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-004", XPath: "compare('abc','aBC',concat($collation,'strength=quaternary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-005", XPath: "compare('abc','aBC',concat($collation,'strength=identical;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-006", XPath: "compare('abc','aBC',concat($collation,'strength=1;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-007", XPath: "compare('abc','aBC',concat($collation,'strength=2;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-008", XPath: "compare('abc','aBC',concat($collation,'strength=3;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-009", XPath: "compare('abc','aBC',concat($collation,'strength=4;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-010", XPath: "compare('abc','aBC',concat($collation,'strength=5;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-011", XPath: "compare('a-bc','abc',concat($collation,'strength=1;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-012", XPath: "compare('a-bc','abc',concat($collation,'strength=2;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-013", XPath: "compare('a-bc','abc',concat($collation,'strength=3;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-014", XPath: "compare('a-bc','abc',concat($collation,'strength=4;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-015", XPath: "compare('a-bc','abc',concat($collation,'strength=5;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-016", XPath: "compare('pêche','péché',concat($collation,'strength=primary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-017", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-018", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;backwards=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-019", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;backwards=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-020", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;normalization=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-021", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;normalization=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-022", XPath: "compare('Epee','épee',concat($collation,'strength=primary;caseLevel=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-023", XPath: "compare('Epee','épee',concat($collation,'strength=primary;caseLevel=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-024", XPath: "compare('Epee','Épee',concat($collation,'strength=primary;caseLevel=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-025", XPath: "compare('Epee','Épee',concat($collation,'strength=primary;caseLevel=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-params-026", XPath: "compare('Epee','épee',concat($collation,'strength=secondary;caseLevel=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-027", XPath: "compare('Epee','épee',concat($collation,'strength=secondary;caseLevel=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-028", XPath: "compare('Epee','Épee',concat($collation,'strength=secondary;caseLevel=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-029", XPath: "compare('Epee','Épee',concat($collation,'strength=secondary;caseLevel=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-030", XPath: "compare('ab','Ab',concat($collation,'caseFirst=upper;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-031", XPath: "compare('ab','Ab',concat($collation,'caseFirst=lower;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-032", XPath: "compare('ab1a','ab12a',concat($collation,'numeric=yes;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-params-033", XPath: "compare('ab1a','ab12a',concat($collation,'numeric=no;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-params-034", XPath: `collation-key('CHAP1', concat($collation,'strength=secondary;numeric=yes;fallback=no')) =
         collation-key('chap1', concat($collation,'strength=secondary;numeric=yes;fallback=no'))`, Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "UCA-maxVariable-001", XPath: "compare('database','data type',concat($collation,'maxVariable=space;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-maxVariable-002", XPath: "compare('database','data type',concat($collation,'maxVariable=space;alternate=non-ignorable;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-maxVariable-003", XPath: "compare('database','data base',concat($collation,'maxVariable=space;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-004", XPath: "compare('database','data base',concat($collation,'maxVariable=space;alternate=shifted;strength=4;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-maxVariable-005", XPath: "compare('database','data-type',concat($collation,'maxVariable=space;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-maxVariable-006", XPath: "compare('database','data-type',concat($collation,'maxVariable=punct;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-maxVariable-007", XPath: "compare('database','data-base',concat($collation,'maxVariable=punct;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-008", XPath: "compare('data base','data-base',concat($collation,'maxVariable=punct;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-009", XPath: "compare('data base','data-base',concat($collation,'maxVariable=punct;alternate=shifted;strength=4;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-maxVariable-010", XPath: "compare('data=base','database',concat($collation,'maxVariable=punct;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-maxVariable-011", XPath: "compare('data=base','database',concat($collation,'maxVariable=symbol;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-012", XPath: "compare('data=base','data base',concat($collation,'maxVariable=symbol;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-013", XPath: "compare('data=base','data$base',concat($collation,'maxVariable=symbol;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-maxVariable-014", XPath: "compare('data=base','data$base',concat($collation,'maxVariable=currency;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-015", XPath: "compare('$10000','€10000',concat($collation,'maxVariable=currency;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-maxVariable-016", XPath: "compare('$10000','€9000',concat($collation,'maxVariable=currency;numeric=yes;alternate=shifted;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-misc-lang-001", XPath: "compare('pêche','péché',concat($collation,'strength=primary;lang=fr;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
		{Name: "UCA-misc-lang-002", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;lang=fr;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("1"))}},
		{Name: "UCA-misc-lang-003", XPath: "compare('pêche','péché',concat($collation,'strength=secondary;lang=fr-CA;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("-1"))}},
		{Name: "UCA-misc-lang-004", XPath: "compare('pêche','péché',concat($collation,'strength=primary;lang=en-US;fallback=no'))", Skip: "requires external parameters", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("0"))}},
	})
}

func TestQT3_misc_XMLEdition(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "line-ending-P002", XPath: "deep-equal(string-to-codepoints('\r\n'), (13, 10))", Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}
