// Code generated by tools/qt3gen; DO NOT EDIT.

package xpath3_test

import "testing"

func TestQT3_map_merge(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-merge-001", XPath: "map:merge()", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-merge-002", XPath: "map:merge(())", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:date, element()+)")}},
		{Name: "map-merge-003-hof", XPath: "map:merge(map:entry(\"foo\", 1 to 5))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertType("function(xs:anyURI) as xs:integer*")}},
		{Name: "map-merge-003", XPath: "map:merge(map:entry(\"foo\", 1 to 5))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)")}},
		{Name: "map-merge-004", XPath: "map:merge((map:entry(\"foo\", 1 to 5), map:entry(\"bar\", 6 to 10)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertSkip()}},
		{Name: "map-merge-005", XPath: "map:merge(for $i in 1 to 20 return map:entry($i, $i*$i))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-006", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)), map{\"duplicates\": \"use-last\"})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-006b", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)), map{\"duplicates\": \"use-first\"})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-006c", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)), map{\"duplicates\": \"combine\"})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-006d", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)), map{\"duplicates\": \"use-any\"})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "map-merge-006e", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "map-merge-006f", XPath: "map:merge((map:entry(\"foo\", 3), map:entry(\"foo\", 4)), map{\"duplicates\": \"reject\"})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-merge-007", XPath: `let $foo := map:entry("foo", 3), $bar := map:entry("foo", 4), $foobar := map:merge(($foo, $bar))
              return ($foobar, $bar, $foo)[3]`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-008", XPath: `let $foo := map:merge(for $i in 1 to 20 return map:entry($i, $i*$i)), $bar := map:entry(8, 63), $foobar := map:merge(($foo, $bar))
              return ($foobar, $bar, $foo)[3]`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-009", XPath: `let $foo := map:merge(for $i in 1 to 20 return map:entry($i, $i*$i)), $bar := map:entry(8, 63), $foobar := map:merge(($foo, $bar))
              return ($foobar, $bar, $foo)[2]`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-010", XPath: `let $foo := map:merge(for $i in 1 to 20 return map:entry($i, $i*$i)), $bar := map:merge(()), $foobar := map:merge(($foo, $bar))
              return $foobar`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-011", XPath: `map:merge((map:entry(3, "three"), map:entry(3.0e0, "threeD"), map:entry(xs:float('3.0'), "threeF")),
            map{"duplicates" : "use-last"})`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:float, xs:string)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-merge-012", XPath: `map:merge(for $n in distinct-values(//*/node-name()) 
                      return map:entry($n, //*[node-name() eq $n]))`, DocPath: "docs/auction.xml", Namespaces: map[string]string{"anyzone": "http://www.example.com/auctioneers#anyzone", "eachbay": "http://www.example.com/auctioneers#eachbay", "ma": "http://www.example.com/AuctionWatch", "map": "http://www.w3.org/2005/xpath-functions/map", "xlink": "http://www.w3.org/1999/xlink", "yabadoo": "http://www.example.com/auctioneers#yabadoo"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(xs:QName, element()+)"), qt3AssertSkip()}},
		{Name: "map-merge-013", XPath: "map:merge(for $n in 1 to 20 return map:entry($n, map{$n :string($n), $n+1:string($n+1), $n+2:string($n+2)}))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertType("map(xs:integer, map(xs:integer, xs:string))"), qt3AssertSkip()}},
		{Name: "map-merge-016", XPath: "deep-equal(map{}, map:merge(()))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-merge-017", XPath: "deep-equal(map{\"a\":1}, map:entry(\"a\", 1))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-merge-018", XPath: "deep-equal(map{\"a\":1,\"b\":2,\"c\":(3,4,5)}, map{\"c\":(3,4,5),\"a\":1,\"b\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-merge-019", XPath: "deep-equal(map{\"a\":1}, map:merge(()))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-merge-020", XPath: `deep-equal(map:merge(for $i in 1 to 1000 return map:entry($i, $i+1)),
                         map:merge(for $i in 2 to 1001 return map:entry($i, $i+1)))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-merge-021", XPath: `deep-equal(map:merge(for $i in 1 to 1000 return map:entry($i, $i+1)),
                         map:merge(((for $i in 1 to 1000 return map:entry($i, $i+1)), map:entry(400, 402)),
                         map{"duplicates":"use-last"}))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-merge-022", XPath: `deep-equal(map:merge(for $i in 1 to 1000 return map:entry($i, $i+1)),
                         map:merge(for $i in 0 to 1000 return map:entry($i, $i+1)))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-merge-023", XPath: `deep-equal(map:merge(for $i in 1 to 1000 return map:entry($i, $i+1)),
                         map:merge(for $i in 2 to 1000 return map:entry($i, $i+1)))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-merge-024-hof", XPath: "map:merge(map:entry(\"foo\", 1 to 5))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertType("function(xs:anyURI) as item()*")}},
		{Name: "map-merge-024", XPath: "map:merge(map:entry(\"foo\", 1 to 5))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)")}},
		{Name: "map-merge-025", XPath: "map:merge((1 to 2000)!map:entry('z', .), map{'duplicates':'combine'})?z", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("1 to 2000")}},
		{Name: "map-merge-026", XPath: `map:merge((1 to 100)!map:entry('z', .), 
            if (current-date() lt xs:date('1900-01-01')) 
            then map{'duplicates':'combine'} 
            else ())?z`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-merge-027", XPath: `let $m := map{'a': (1, 2), 'b': 2, 'c': 1, 'd': 3} 
            return map:merge( 
                for $key in sort(map:keys($m), (), fn:data#1) return for $val in map:get($m, $key) return map{$val : $key}, 
                map{'duplicates': 'combine'})`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:string*)"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
	})
}

func TestQT3_map_contains(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-contains-001", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-002", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-003", XPath: "map:contains(map{}, 23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-004", XPath: "map:contains(map:entry(\"foo\", \"bar\"), \"baz\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-005", XPath: "map:contains(map:entry(\"foo\", \"bar\"), \"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-006", XPath: "map:contains(map:entry(\"foo\", \"bar\"), xs:untypedAtomic(\"foo\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-007", XPath: "map:contains(map:entry(xs:untypedAtomic(\"foo\"), \"bar\"), \"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-008", XPath: "map:contains(map:entry(xs:untypedAtomic(\"12\"), \"bar\"), 12)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-009", XPath: "map:contains(map:entry(12, \"bar\"), xs:untypedAtomic(\"12\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-010", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4.0e0)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-011", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4.0e0:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-012", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",\"urn:weds\":\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:anyURI(\"urn:weds\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-013", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, \"urn:weds\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-014", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-015", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-016", XPath: `map:contains(
                map:merge(((for $i in 1 to 1000 return map:entry($i, $i*$i)),
                         (for $i in 2000 to 3000 return map:entry($i, $i+30)),
                         (for $i in 2500 to 3500 return map:entry($i, $i+30)))),
                         3260)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-017", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:duration('P1Y'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:yearMonthDuration('P12M'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-018", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",function-name(abs#1):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:QName('fn:abs'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-019", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:(),5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-contains-020", XPath: "map:contains(map{\"su\":\"Sunday\",\"mo\":\"Monday\",\"tu\":\"Tuesday\",\"we\":\"Wednesday\",\"th\":\"Thursday\",\"fr\":\"Friday\",\"sa\":\"Saturday\"}, \"TH\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "map-contains-901", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, (1 to 5)[10])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-contains-902", XPath: "map:contains(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, (1 to 5)[. mod 2 = 0])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-contains-903", XPath: "map:contains((\"a\", \"b\", \"c\"), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-contains-904", XPath: "map:contains((), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-contains-905", XPath: "map:contains(abs#1, \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-contains-906", XPath: "map:contains((map{}, map{\"a\":\"b\"}), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
	})
}

func TestQT3_map_find(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-find-001", XPath: "map:find((), 17)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[]")}},
		{Name: "map-find-002", XPath: "map:find(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"Wednesday\"]")}},
		{Name: "map-find-003", XPath: "map:find(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 86)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[]")}},
		{Name: "map-find-004", XPath: `map:find((map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:"Saturday"},
            map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:"Samedi",1:"Dimanche"}), 1)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"Sunday\", \"Dimanche\"]")}},
		{Name: "map-find-005", XPath: `map:find([map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:"Saturday"},
            map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:"Samedi",1:"Dimanche"}], 1)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"Sunday\", \"Dimanche\"]")}},
		{Name: "map-find-006", XPath: `map:find([map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:"Saturday"},
            map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:"Samedi",1:"Dimanche"}, 1], 1)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"Sunday\", \"Dimanche\"]")}},
		{Name: "map-find-007", XPath: `map:find(map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:"Saturday", "fr":
            map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:"Samedi",1:"Dimanche"}}, 1)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckDeepEq("[\"Sunday\", \"Dimanche\"]"), qt3CheckDeepEq("[\"Dimanche\", \"Sunday\"]"))}},
		{Name: "map-find-008", XPath: `map:find([map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:"Saturday", "fr":
            [map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:"Samedi",1:"Dimanche"}, 78]}, 82], 7)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckDeepEq("[\"Saturday\", \"Samedi\"]"), qt3CheckDeepEq("[\"Samedi\", \"Saturday\"]"))}},
		{Name: "map-find-009", XPath: `map:find([map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:["Saturday", "Sat"], "fr":
            [map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:["Samedi", "Sa"],1:"Dimanche"}, 78]}, 82], 7)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckDeepEq("[[\"Saturday\", \"Sat\"], [\"Samedi\", \"Sa\"]]"), qt3CheckDeepEq("[[\"Samedi\", \"Sa\"], [\"Saturday\", \"Sat\"]]"))}},
		{Name: "map-find-010", XPath: `map:find([map{1:"Sunday",2:"Monday",3:"Tuesday",4:"Wednesday",5:"Thursday",6:"Friday",7:("Saturday", "Sat"), "fr":
            [map{2:"Lundi",3:"Mardi",4:"Mercredi",5:"Jeudi",6:"Vendredi",7:("Samedi", "Sa"),1:"Dimanche"}, 78]}, 82], 7)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckDeepEq("[(\"Saturday\", \"Sat\"), (\"Samedi\", \"Sa\")]"), qt3CheckDeepEq("[(\"Samedi\", \"Sa\"), (\"Saturday\", \"Sat\")]"))}},
		{Name: "map-find-101", XPath: "fn:json-doc(\"http://www.w3.org/qt3/json/data004-json\") => map:find(\"servlet-name\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"cofaxCDS\", \"cofaxEmail\", \"cofaxAdmin\", \"fileServlet\", \"cofaxTools\"]")}},
		{Name: "map-find-102", XPath: "fn:json-doc(\"http://www.w3.org/qt3/json/data004-json\") => map:find(\"init-param\") => map:find(\"mailHost\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertDeepEq("[\"mail1\"]")}},
	})
}

func TestQT3_map_get(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-get-001", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-002", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-003", XPath: "map:get(map{}, 23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-004", XPath: "map:get(map:entry(\"foo\", \"bar\"), \"baz\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-005", XPath: "map:get(map:entry(\"foo\", \"bar\"), \"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-get-006", XPath: "map:get(map:entry(\"foo\", \"bar\"), xs:untypedAtomic(\"foo\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-get-007", XPath: "map:get(map:entry(xs:untypedAtomic(\"foo\"), \"bar\"), \"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-get-008", XPath: "map:get(map:entry(xs:untypedAtomic(\"12\"), \"bar\"), 12)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-009", XPath: "map:get(map:entry(12, \"bar\"), xs:untypedAtomic(\"12\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-010", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4.0e0)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-011", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4.0e0:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-012", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",\"urn:weds\":\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:anyURI(\"urn:weds\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-013", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, \"urn:weds\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-014", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-015", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-016", XPath: `map:get(
                map:merge(((for $i in 1 to 1000 return map:entry($i, $i*$i)),
                         (for $i in 2000 to 3000 return map:entry($i, $i+30)),
                         (for $i in 2500 to 3500 return map:entry($i, $i+30)))),
                         3260)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("3290")}},
		{Name: "map-get-017", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:duration('P1Y'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:yearMonthDuration('P12M'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-018", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",function-name(abs#1):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, xs:QName('fn:abs'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-get-019", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:(),5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-020", XPath: "map:get(map{\"su\":\"Sunday\",\"mo\":\"Monday\",\"tu\":\"Tuesday\",\"we\":\"Wednesday\",\"th\":\"Thursday\",\"fr\":\"Friday\",\"sa\":\"Saturday\"}, \"TH\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-get-021", XPath: "map:get(map{\"foo\":\"bar\", \"bar\":\"foo\"}, xs:untypedAtomic(\"foo\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-get-022", XPath: "map:get(map{xs:untypedAtomic(\"foo\"):\"bar\", xs:untypedAtomic(\"bar\"):\"foo\"}, \"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-get-023", XPath: "map:get(map{current-dateTime():100, current-dateTime()=>adjust-dateTime-to-timezone(()):101}, current-dateTime())", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("100")}},
		{Name: "map-get-024", XPath: `map:get(map{current-date():100, current-date()=>adjust-date-to-timezone(()):101}, 
                    current-date()=>adjust-date-to-timezone(()))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("101")}},
		{Name: "map-get-025", XPath: "map:get(map{number('NaN'):100, 12e6:101}, xs:float('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("100")}},
		{Name: "map-get-100", XPath: `fn:for-each(("we", "th"),
                map{"su":"Sunday","mo":"Monday","tu":"Tuesday","we":"Wednesday","th":"Thursday","fr":"Friday","sa":"Saturday"}
            )`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(2), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-get-901", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, (1 to 5)[10])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-get-902", XPath: "map:get(map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}, (1 to 5)[. mod 2 = 0])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-get-903", XPath: "map:get((\"a\", \"b\", \"c\"), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-get-904", XPath: "map:get((), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-get-905", XPath: "map:get(abs#1, \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-get-906", XPath: "map:get((map{}, map{\"a\":\"b\"}), \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
	})
}

func TestQT3_map_entry(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-entry-001-hof", XPath: "map:entry(3, 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertType("function(xs:anyAtomicType) as xs:integer?"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-001", XPath: "map:entry(3, 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-002", XPath: "map:entry(3, ())", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, empty-sequence())"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-003", XPath: "map:entry(\"foo\", (\"x\", \"y\", \"z\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:string*)"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-004", XPath: "map:entry(xs:untypedAtomic(\"foo\"), map{})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:untypedAtomic, map(*))"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-005", XPath: "map:entry(number('NaN'), 'NaN')", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-006", XPath: "map:entry(xs:float('NaN'), 'NaN')", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-007-hof", XPath: "map:entry(3, 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertType("function(xs:anyAtomicType) as item()*"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-entry-007", XPath: "map:entry(3, 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
	})
}

func TestQT3_map_size(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-size-001", XPath: "map:size(map{})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("0"), qt3AssertType("xs:integer")}},
		{Name: "map-size-002", XPath: "map:size(map:merge(()))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("0"), qt3AssertType("xs:integer")}},
		{Name: "map-size-003", XPath: "map:size(map{\"a\":1})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("1"), qt3AssertType("xs:integer")}},
		{Name: "map-size-004", XPath: "map:size(map:entry(\"a\", \"1\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("1"), qt3AssertType("xs:integer")}},
		{Name: "map-size-005", XPath: "map:size(map:merge((map:entry(\"a\", \"1\"), map:entry(\"b\", 2))))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2"), qt3AssertType("xs:integer")}},
		{Name: "map-size-006", XPath: "map:size(map{\"a\":1, \"b\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2"), qt3AssertType("xs:integer")}},
		{Name: "map-size-007", XPath: "map:size(map{\"a\":1, \"a\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-size-008", XPath: "map:size(map:merge((map:entry(\"a\",1), map:entry(\"a\",2))))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("1"), qt3AssertType("xs:integer")}},
		{Name: "map-size-009", XPath: "map:size(map:remove(map{\"a\":1,\"b\":2}, \"b\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("1"), qt3AssertType("xs:integer")}},
		{Name: "map-size-010", XPath: "map:size(map:remove(map:entry(1,2),1))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("0"), qt3AssertType("xs:integer")}},
		{Name: "map-size-011", XPath: "map:size(map:remove(map:remove(map{\"a\":1,\"b\":2},\"b\"),\"a\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("0"), qt3AssertType("xs:integer")}},
		{Name: "map-size-012", XPath: "map:size(map{number('NaN'):1,\"b\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2"), qt3AssertType("xs:integer")}},
		{Name: "map-size-013", XPath: "map:size(map:remove(map{\"a\":1,\"b\":2}, \"c\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2"), qt3AssertType("xs:integer")}},
		{Name: "map-size-014", XPath: "map{current-dateTime():100, current-dateTime()=>adjust-dateTime-to-timezone(()):101} => map:size()", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2")}},
		{Name: "map-size-015", XPath: `map:merge(((1 to 20)!map{.: 0}, (10 to 30)!map{.: 0}), map{'duplicates':'combine'}) (:30:)
            => map:remove((4, 8, 12)) (:27:)
            => map:put(50, 0) (:28:)
            => map:put(4, 0) (:29:)
            => map:put(1, 0) (:29:)
            => map:size()`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("29")}},
	})
}

func TestQT3_map_keys(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-keys-001", XPath: "map:keys(map{})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-keys-002", XPath: "map:keys(map:merge(()))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-keys-003", XPath: "map:keys(map{\"a\":1})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-keys-004", XPath: "map:keys(map:entry(\"a\", \"1\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-keys-005", XPath: "map:keys(map:merge((map:entry(\"a\", \"1\"), map:entry(\"b\", 2))))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-keys-006", XPath: "map:keys(map{\"a\":1, \"b\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-keys-007", XPath: "map:keys(map{\"a\":1, \"a\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-keys-008", XPath: "map:keys(map:merge((map:entry(\"a\",1), map:entry(\"a\",2))))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-keys-009", XPath: "map:keys(map:remove(map{\"a\":1,\"b\":2}, \"b\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-keys-010", XPath: "map:keys(map:remove(map:entry(1,2),1))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-keys-011", XPath: "map:keys(map:remove(map:remove(map{\"a\":1,\"b\":2},\"b\"),\"a\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-keys-012", XPath: "map:keys(map{number('NaN'):1,\"b\":2})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(2)}},
		{Name: "map-keys-013", XPath: "map:keys(map:remove(map{\"a\":1,\"b\":2}, \"c\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-keys-014", XPath: "map:keys(map:merge(for $n in 1 to 500000 return map:entry($n, $n+1)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(500000)}},
	})
}

func TestQT3_map_put(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-put-002-hof", XPath: "map:put(map{}, \"foo\", 1 to 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertType("function(xs:string) as item()*")}},
		{Name: "map-put-002", XPath: "map:put(map{}, \"foo\", 1 to 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)")}},
		{Name: "map-put-003-hof", XPath: "map:put(map{}, \"foo\", 1 to 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertType("function(xs:string) as xs:integer*")}},
		{Name: "map-put-003", XPath: "map:put(map{}, \"foo\", 1 to 5)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)")}},
		{Name: "map-put-004", XPath: "map:put(map:entry(\"foo\", 1 to 5), \"bar\", 6 to 10)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer+)"), qt3AssertSkip()}},
		{Name: "map-put-006", XPath: "map:put(map:entry(\"foo\", 3), \"foo\", 4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-007", XPath: `let $foo := map:entry("foo", 3), $foobar := map:put($foo, "foo", 4)
              return ($foobar, $foo)[2]`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-008", XPath: `let $foo := map:merge(for $i in 1 to 20 return map:entry($i, $i*$i)), $foobar := map:put($foo, 8, 63)
              return ($foobar, $foo)[2]`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-010", XPath: "map:put(map{}, 1, 2)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-011", XPath: "map:put(map{3 : \"three\"},  xs:float('3.0'), \"threeF\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(*)"), qt3AssertType("map(xs:float, xs:string)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-012", XPath: `map:put(map:merge(for $n in distinct-values(/*//*/node-name()) 
                                return map:entry($n, /*//*[node-name() eq $n])), node-name(/*), /*)`, DocPath: "docs/auction.xml", Namespaces: map[string]string{"anyzone": "http://www.example.com/auctioneers#anyzone", "eachbay": "http://www.example.com/auctioneers#eachbay", "ma": "http://www.example.com/AuctionWatch", "map": "http://www.w3.org/2005/xpath-functions/map", "xlink": "http://www.w3.org/1999/xlink", "yabadoo": "http://www.example.com/auctioneers#yabadoo"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("map(xs:QName, element()+)"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-013", XPath: `map:put(
            map:merge(for $n in 1 to 20 return map:entry($n, map{$n : string($n), $n+1 : string($n+1), $n+2 : string($n+2)})),
            21, map{21 : '21'})`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertType("map(xs:integer, map(xs:integer, xs:string))"), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-put-017", XPath: "deep-equal(map{\"a\":1}, map:put(map{}, 'a', 1))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-put-018", XPath: "deep-equal(map:put(map{\"a\":1,\"b\":2,\"c\":(3,4,5)}, \"d\", 6), map:put(map{\"d\":6,\"c\":(3,4,5),\"a\":1}, \"b\", 2))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-put-019", XPath: "deep-equal(map{}, map:remove(map:put(map:merge(()), 1, 2), 1))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-put-020", XPath: `deep-equal(map:put(map:merge(for $i in 1 to 1000 return map:entry($i, $i+1)), 1001, 1002),
                         map:merge(for $i in 1 to 1001 return map:entry($i, $i+1)))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-put-021", XPath: "map{} => map:put(xs:double('NaN'), 10) => map:put(xs:float('NaN'), 20) => map:size()", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("1")}},
		{Name: "map-put-022", XPath: "deep-equal(map{xs:double('NaN'): 10}, map{xs:float('NaN'):10e0})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-put-023", XPath: `map{xs:float('1.0'):0, xs:double('1.00000000001'):1} 
            => map:put(xs:decimal('1.0000000000100000000001'), 2) 
            => map:size()`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("3")}},
	})
}

func TestQT3_map_remove(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-remove-001", XPath: "map:remove(map{}, 1)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "map-remove-002", XPath: "map:remove(map:merge(()), \"abcd\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "map-remove-003", XPath: "map:remove(map{\"a\":1}, \"a\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "map-remove-005", XPath: "map:remove(map:entry(\"a\", \"1\"), \"b\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-remove-006", XPath: "map:remove(map:merge((map:entry(\"a\", \"1\"), map:entry(\"b\", 2))), \"b\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-remove-007", XPath: "map:remove(map:merge((map:entry(\"a\", \"1\"), map:entry(\"b\", 2))), \"c\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-remove-008", XPath: "map:remove(map:merge((map:entry(12, 1), map:entry(13, 2))), 12e0)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertType("map(xs:integer, xs:integer)"), qt3AssertSkip()}},
		{Name: "map-remove-009", XPath: "map:remove(map:merge((map:entry(\"a\",1), map:entry(\"b\",2))), xs:untypedAtomic(\"b\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertType("map(xs:string, xs:integer)"), qt3AssertSkip()}},
		{Name: "map-remove-010", XPath: "map:remove(map{\"a\":1,\"b\":\"xyz\"}, \"b\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertType("map(xs:string, xs:integer)")}},
		{Name: "map-remove-011", XPath: "map:remove(map{\"a\":1,12:\"xyz\"}, 12)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertType("map(xs:string, xs:integer)")}},
		{Name: "map-remove-012", XPath: "map:remove(map:merge(for $n in 1 to 500000 return map:entry($n, $n+1)), 123456)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "map-remove-013", XPath: "deep-equal(map:remove(map{\"a\":1,\"b\":(2,3)}, \"a\"), map:entry(\"b\", (2,3)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-remove-014", XPath: `map{current-dateTime():100, current-dateTime()=>adjust-dateTime-to-timezone(()):101} 
            => map:remove(current-dateTime()) 
            => map:get(current-dateTime()=>adjust-dateTime-to-timezone(()))`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("101")}},
		{Name: "map-remove-015", XPath: `map{xs:double('1.25'):0}
            => map:remove(xs:float('1.25')) 
            => map:size()`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("0")}},
		{Name: "map-remove-016", XPath: `map{xs:float('1.0'):0, xs:double('1.00000000001'):1} 
            => map:remove(xs:decimal('1.0000000000100000000001')) 
            => map:size()`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("2")}},
		{Name: "map-remove-017", XPath: "deep-equal(map:remove(map{\"a\":1,\"b\":(2,3), \"c\":1 to 5}, (\"a\", \"c\")), map:entry(\"b\", (2,3)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-remove-018", XPath: "map:size(map:remove(map{\"a\":1,\"b\":(2,3), \"c\":1 to 5}, ())) = 3", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "map-remove-019", XPath: "deep-equal(map:remove(map{\"a\":1,\"b\":(2,3), \"c\":1 to 5}, (\"a\", \"c\", \"d\")), map:entry(\"b\", (2,3)))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}

func TestQT3_map_for_each(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-for-each-001", XPath: "map:for-each(map{}, concat#2)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-for-each-002", XPath: "map:for-each(map:merge(()), function($k,$v){$k||$v})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-for-each-003", XPath: "map:for-each(map{\"a\":1}, function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-for-each-004", XPath: "map:for-each(map:entry(\"a\", \"1\"), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-for-each-005", XPath: "map:for-each(map:merge((map:entry(\"a\", \"1\"), map:entry(\"b\", 2))), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-for-each-006", XPath: "map:for-each(map{\"a\":1, \"b\":2}, function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-for-each-007", XPath: "map:for-each(map{\"a\":1, \"a\":2}, function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-for-each-008", XPath: "map:for-each(map:merge((map:entry(\"a\",1), map:entry(\"a\",2))), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-for-each-009", XPath: "map:for-each(map:remove(map{\"a\":1,\"b\":2}, \"b\"), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(1), qt3AssertType("xs:string"), qt3AssertEq("\"a\"")}},
		{Name: "map-for-each-010", XPath: "map:for-each(map:remove(map:entry(1,2),1), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-for-each-011", XPath: "map:for-each(map:remove(map:remove(map{\"a\":1,\"b\":2},\"b\"),\"a\"), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-for-each-012", XPath: "map:for-each(map{number('NaN'):1,\"b\":2}, function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertCount(2)}},
		{Name: "map-for-each-013", XPath: "map:for-each(map:remove(map{\"a\":1,\"b\":2}, \"c\"), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-for-each-014", XPath: "map:for-each(map:merge(for $n in 1 to 500000 return map:entry($n, $n+1)), function($k,$v){$k})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(500000)}},
		{Name: "map-for-each-015", XPath: "map:for-each(map{\"a\":1, \"b\":2}, function($k,$v){$k||$v})", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(2)}},
		{Name: "map-for-each-016", XPath: "map:merge(map:for-each(map{\"a\":1, \"b\":2}, function($k,$v){map{$v : $k}}))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertCount(1)}},
	})
}

func TestQT3_map_call(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "map-call-001", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-002", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-003", XPath: "map{}(23)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-004", XPath: "map:entry(\"foo\", \"bar\")(\"baz\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-005", XPath: "map:entry(\"foo\", \"bar\")(\"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-call-006", XPath: "map:entry(\"foo\", \"bar\")(xs:untypedAtomic(\"foo\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-call-007", XPath: "map:entry(xs:untypedAtomic(\"foo\"), \"bar\")(\"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-call-008", XPath: "map:entry(xs:untypedAtomic(\"12\"), \"bar\")(12)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-009", XPath: "map:entry(12, \"bar\")(xs:untypedAtomic(\"12\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-010", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(4.0e0)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-011", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4.0e0:\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-012", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",\"urn:weds\":\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(xs:anyURI(\"urn:weds\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-013", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(\"urn:weds\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-014", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:anyURI(\"urn:weds\"):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-015", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(number('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-016", XPath: `map:merge(((for $i in 1 to 1000 return map:entry($i, $i*$i)),
                         (for $i in 2000 to 3000 return map:entry($i, $i+30)),
                         (for $i in 2500 to 3500 return map:entry($i, $i+30))))
                         (3260)`, Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("3290")}},
		{Name: "map-call-017", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",xs:duration('P1Y'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(xs:yearMonthDuration('P12M'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-018", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",function-name(abs#1):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(xs:QName('fn:abs'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("Wednesday")}},
		{Name: "map-call-019", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",4:(),5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}(4)", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-020", XPath: "map{\"su\":\"Sunday\",\"mo\":\"Monday\",\"tu\":\"Tuesday\",\"we\":\"Wednesday\",\"th\":\"Thursday\",\"fr\":\"Friday\",\"sa\":\"Saturday\"}(\"TH\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "map-call-021", XPath: "map{\"foo\":\"bar\", \"bar\":\"foo\"}(xs:untypedAtomic(\"foo\"))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-call-022", XPath: "map{xs:untypedAtomic(\"foo\"):\"bar\", xs:untypedAtomic(\"bar\"):\"foo\"}(\"foo\")", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("bar")}},
		{Name: "map-call-023", XPath: "map{current-dateTime():100, current-dateTime()=>adjust-dateTime-to-timezone(()):101}(current-dateTime())", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertStringValue("100")}},
		{Name: "map-call-025", XPath: "map{number('NaN'):100, 12e6:101}(xs:float('NaN'))", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, Assertions: []qt3Assertion{qt3AssertEq("100")}},
		{Name: "map-call-901", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}((1 to 5)[10])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
		{Name: "map-call-902", XPath: "map{1:\"Sunday\",2:\"Monday\",3:\"Tuesday\",number('NaN'):\"Wednesday\",5:\"Thursday\",6:\"Friday\",7:\"Saturday\"}((1 to 5)[. mod 2 = 0])", Namespaces: map[string]string{"map": "http://www.w3.org/2005/xpath-functions/map"}, ExpectError: true},
	})
}
