// Code generated by tools/qt3gen; DO NOT EDIT.

package xpath3_test

import "testing"

func TestQT3_xs_anyURI(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "cbcl-anyURI-001", XPath: "xs:anyURI(())", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "cbcl-anyURI-002", XPath: "xs:anyURI(\"odd-scheme+1.://www.example.org/\")", Assertions: []qt3Assertion{qt3AssertStringValue("odd-scheme+1.://www.example.org/")}},
		{Name: "cbcl-anyURI-003", XPath: "xs:anyURI(\"http://%0Ad%E2%9C%90%F0%98%9A%A0/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://%0Ad%E2%9C%90%F0%98%9A%A0/")}},
		{Name: "cbcl-anyURI-004b", XPath: "xs:anyURI(\"http://!$&'()*+,;=/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://!$&'()*+,;=/")}},
		{Name: "cbcl-anyURI-005", XPath: "xs:anyURI(\"http://www.example.org/%0Ad%E2%9C%90%F0%98%9A%A0/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/%0Ad%E2%9C%90%F0%98%9A%A0/")}},
		{Name: "cbcl-anyURI-006b", XPath: "xs:anyURI(\"http://www.example.org/!/$/&/'/(/)/*/+/,/;/=/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/!/$/&/'/(/)/*/+/,/;/=/")}},
		{Name: "cbcl-anyURI-007", XPath: "xs:anyURI(\"http://www.example.org/:/@/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/:/@/")}},
		{Name: "cbcl-anyURI-008", XPath: "xs:anyURI(\"http://www.example.org/?%0Ad%E2%9C%90%F0%98%9A%A0/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/?%0Ad%E2%9C%90%F0%98%9A%A0/")}},
		{Name: "cbcl-anyURI-009b", XPath: "xs:anyURI(\"http://www.example.org/?!$&'()*+,;=\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/?!$&'()*+,;=")}},
		{Name: "cbcl-anyURI-010", XPath: "xs:anyURI(\"http://www.example.org/?:@\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/?:@")}},
		{Name: "cbcl-anyURI-011", XPath: "xs:anyURI(\"http://www.example.org/#%0Ad%E2%9C%90%F0%98%9A%A0/\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/#%0Ad%E2%9C%90%F0%98%9A%A0/")}},
		{Name: "cbcl-anyURI-012b", XPath: "xs:anyURI(\"http://www.example.org/#!$&'()*+,;=\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/#!$&'()*+,;=")}},
		{Name: "cbcl-anyURI-013", XPath: "xs:anyURI(\"http://www.example.org/#:@\")", Assertions: []qt3Assertion{qt3AssertStringValue("http://www.example.org/#:@")}},
	})
}

func TestQT3_xs_base64Binary(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "base64-001", XPath: "xs:base64Binary(xs:hexBinary(\"\"))", Assertions: []qt3Assertion{qt3AssertStringValue("")}},
		{Name: "base64-002", XPath: "xs:base64Binary(xs:hexBinary(\"00\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AA==")}},
		{Name: "base64-003", XPath: "xs:base64Binary(xs:hexBinary(\"01\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQ==")}},
		{Name: "base64-004", XPath: "xs:base64Binary(xs:hexBinary(\"ff\"))", Assertions: []qt3Assertion{qt3AssertStringValue("/w==")}},
		{Name: "base64-005", XPath: "xs:base64Binary(xs:hexBinary(\"0000\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AAA=")}},
		{Name: "base64-006", XPath: "xs:base64Binary(xs:hexBinary(\"00ff\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AP8=")}},
		{Name: "base64-007", XPath: "xs:base64Binary(xs:hexBinary(\"80c0\"))", Assertions: []qt3Assertion{qt3AssertStringValue("gMA=")}},
		{Name: "base64-008", XPath: "xs:base64Binary(xs:hexBinary(\"aabbcc\"))", Assertions: []qt3Assertion{qt3AssertStringValue("qrvM")}},
		{Name: "base64-009", XPath: "xs:base64Binary(xs:hexBinary(\"010203\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQID")}},
		{Name: "base64-010", XPath: "xs:base64Binary(xs:hexBinary(\"01020304\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQIDBA==")}},
		{Name: "base64-011", XPath: "xs:base64Binary(xs:hexBinary(\"0102030405\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQIDBAU=")}},
		{Name: "base64-012", XPath: "xs:base64Binary(xs:hexBinary(\"010203040506\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQIDBAUG")}},
		{Name: "base64-013", XPath: "xs:base64Binary(xs:hexBinary(\"01020304050607\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQIDBAUGBw==")}},
		{Name: "base64-014", XPath: "xs:base64Binary(xs:hexBinary(\"0102030405060708090A0B0C0D0E0F10111213131415161718191A1B1C1D1F202122232425262728292A2B2C2D2E2F\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AQIDBAUGBwgJCgsMDQ4PEBESExMUFRYXGBkaGxwdHyAhIiMkJSYnKCkqKywtLi8=")}},
		{Name: "base64-101", XPath: "xs:base64Binary(\"\")", Assertions: []qt3Assertion{qt3AssertStringValue("")}},
		{Name: "base64-102", XPath: "xs:hexBinary(xs:base64Binary(\"AA==\"))", Assertions: []qt3Assertion{qt3AssertStringValue("00")}},
		{Name: "base64-103", XPath: "xs:hexBinary(xs:base64Binary(\"AQ==\"))", Assertions: []qt3Assertion{qt3AssertStringValue("01")}},
		{Name: "base64-104", XPath: "xs:hexBinary(xs:base64Binary(\"/w==\"))", Assertions: []qt3Assertion{qt3AssertStringValue("FF")}},
		{Name: "base64-105", XPath: "xs:hexBinary(xs:base64Binary(\"AAA=\"))", Assertions: []qt3Assertion{qt3AssertStringValue("0000")}},
		{Name: "base64-106", XPath: "xs:hexBinary(xs:base64Binary(\"AP8=\"))", Assertions: []qt3Assertion{qt3AssertStringValue("00FF")}},
		{Name: "base64-107", XPath: "xs:hexBinary(xs:base64Binary(\"gMA=\"))", Assertions: []qt3Assertion{qt3AssertStringValue("80C0")}},
		{Name: "base64-108", XPath: "xs:hexBinary(xs:base64Binary(\"qrvM\"))", Assertions: []qt3Assertion{qt3AssertStringValue("AABBCC")}},
		{Name: "base64-109", XPath: "xs:hexBinary(xs:base64Binary(\"AQID\"))", Assertions: []qt3Assertion{qt3AssertStringValue("010203")}},
		{Name: "base64-110", XPath: "xs:hexBinary(xs:base64Binary(\"AQIDBA==\"))", Assertions: []qt3Assertion{qt3AssertStringValue("01020304")}},
		{Name: "base64-111", XPath: "xs:hexBinary(xs:base64Binary(\"AQIDBAU=\"))", Assertions: []qt3Assertion{qt3AssertStringValue("0102030405")}},
		{Name: "base64-112", XPath: "xs:hexBinary(xs:base64Binary(\"AQIDBAUG\"))", Assertions: []qt3Assertion{qt3AssertStringValue("010203040506")}},
		{Name: "base64-113", XPath: "xs:hexBinary(xs:base64Binary(\"AQIDBAUGBw==\"))", Assertions: []qt3Assertion{qt3AssertStringValue("01020304050607")}},
		{Name: "base64-114", XPath: "xs:hexBinary(xs:base64Binary(\"AQIDBAUGBwgJCgsMDQ4PEBESExMUFRYXGBkaGxwdHyAhIiMkJSYnKCkqKywtLi8=\"))", Assertions: []qt3Assertion{qt3AssertStringValue("0102030405060708090A0B0C0D0E0F10111213131415161718191A1B1C1D1F202122232425262728292A2B2C2D2E2F")}},
		{Name: "base64-115", XPath: `xs:hexBinary(xs:base64Binary(" AQIDBAUG BwgJCgsM DQ4PEBES ExMUFRYX 
 GBkaGxwdH yAhIiMkJ SYnKCkqK y w t L i 8 = "))`, Assertions: []qt3Assertion{qt3AssertStringValue("0102030405060708090A0B0C0D0E0F10111213131415161718191A1B1C1D1F202122232425262728292A2B2C2D2E2F")}},
		{Name: "base64-901", XPath: "xs:base64Binary(\"AQI\")", ExpectError: true},
		{Name: "base64-902", XPath: "xs:base64Binary(\"AQ=I\")", ExpectError: true},
		{Name: "base64-903", XPath: "xs:base64Binary(\"=AQI\")", ExpectError: true},
		{Name: "base64-904", XPath: "xs:base64Binary(\"qrvM====\")", ExpectError: true},
		{Name: "base64-905", XPath: "xs:base64Binary(\"gMA-\")", ExpectError: true},
		{Name: "base64-906", XPath: "xs:base64Binary(\"AP9=\")", ExpectError: true},
		{Name: "base64-907", XPath: "xs:base64Binary(\"Ay==\")", ExpectError: true},
		{Name: "base64-908", XPath: "xs:base64Binary(codepoints-to-string((119070, 119070, 119070, 119070) (:treble clef:)))", ExpectError: true},
		{Name: "base64-909", XPath: "codepoints-to-string((119070, 119070, 119070, 119070) (:treble clef:)) castable as xs:base64Binary", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "cbcl-base64binary-001", XPath: "count(xs:base64Binary(()))", Assertions: []qt3Assertion{qt3AssertStringValue("0")}},
	})
}

func TestQT3_xs_dateTimeStamp(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "xs-dateTimeStamp-1", XPath: "exists(fn:timezone-from-dateTime(fn:current-dateTime()))", Assertions: []qt3Assertion{qt3AssertEq("true()")}},
		{Name: "xs-dateTimeStamp-2", XPath: "exists(fn:timezone-from-dateTime(xs:dateTimeStamp(\"2011-07-28T12:34:56-08:00\")))", Assertions: []qt3Assertion{qt3AssertEq("true()")}},
		{Name: "xs-dateTimeStamp-3", XPath: "xs:dateTimeStamp(\"2011-07-28T12:34:56\")", ExpectError: true},
		{Name: "xs-dateTimeStamp-4", XPath: "xs:dateTimeStamp(xs:dateTime(\"2011-07-28T12:34:56\"))", ExpectError: true},
		{Name: "xs-dateTimeStamp-5", XPath: "xs:dateTimeStamp(xs:date(\"2011-07-28+01:00\"))", Assertions: []qt3Assertion{qt3AssertStringValue("2011-07-28T00:00:00+01:00")}},
		{Name: "xs-dateTimeStamp-6", XPath: "current-date() castable as xs:dateTimeStamp", Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}

func TestQT3_xs_double(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "xs-double-001", XPath: "fn:string(xs:double(\"-0\"))", Assertions: []qt3Assertion{qt3AssertEq("fn:string(\"-0\")")}},
		{Name: "xs-double-002", XPath: "1 div xs:double(\"-0\") ne 1 div xs:double(\"0\")", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-double-003", XPath: "exists(xs:double(\"+INF\"))", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-double-004", XPath: "exists(xs:double(\"+INF\"))", Skip: "requires XSD 1.0", ExpectError: true},
		{Name: "xs-double-005", XPath: "xs:double(\"2.2250738585072012e-308\")", Skip: "requires XSD 1.0", Assertions: []qt3Assertion{qt3AssertType("xs:double")}},
	})
}

func TestQT3_xs_error(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "xs-error-001", XPath: "xs:error()", ExpectError: true},
		{Name: "xs-error-002", XPath: "xs:error#0", ExpectError: true},
		{Name: "xs-error-003", XPath: "xs:error( (), () )", ExpectError: true},
		{Name: "xs-error-004", XPath: "xs:error#2", ExpectError: true},
		{Name: "xs-error-005", XPath: "fn:exists( xs:error#1 )", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-006", XPath: "xs:error#1 instance of function(xs:anyAtomicType?) as xs:error?", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-007", XPath: "xs:error#1 instance of function(xs:anyAtomicType?) as empty-sequence()", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-008", XPath: "xs:error( () )", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEmpty())}},
		{Name: "xs-error-009", XPath: "xs:error(xs:untypedAtomic(\"\"))", ExpectError: true},
		{Name: "xs-error-010", XPath: "xs:error(\"\")", ExpectError: true},
		{Name: "xs-error-011", XPath: "xs:error(1.0)", ExpectError: true},
		{Name: "xs-error-012", XPath: "xs:error(1e0)", ExpectError: true},
		{Name: "xs-error-013", XPath: "xs:error(1)", ExpectError: true},
		{Name: "xs-error-014", XPath: "xs:error(1) instance of xs:error", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "xs-error-015", XPath: "function() as empty-sequence() { () } instance of function() as xs:error?", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-016", XPath: "function() as empty-sequence() { () } instance of function() as xs:error*", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-024", XPath: "let $x := fn:error() return $x", ExpectError: true},
		{Name: "xs-error-026", XPath: "let $x := fn:error() return true()", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "xs-error-030", XPath: "for $x in fn:error() return fn:true()", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "xs-error-032", XPath: "xs:error(1) castable as xs:error", ExpectError: true},
		{Name: "xs-error-033", XPath: "xs:error(1) castable as xs:integer", ExpectError: true},
		{Name: "xs-error-034", XPath: "xs:error(()) castable as xs:error", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "xs-error-035", XPath: "xs:error(()) castable as xs:error?", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-036", XPath: "fn:error() castable as xs:error", ExpectError: true},
		{Name: "xs-error-037", XPath: "() castable as xs:error?", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-error-038", XPath: "xs:error(1) cast as xs:error", ExpectError: true},
		{Name: "xs-error-039", XPath: "xs:error(1) cast as xs:integer", ExpectError: true},
		{Name: "xs-error-040", XPath: "xs:error(()) cast as xs:error", ExpectError: true},
		{Name: "xs-error-041", XPath: "xs:error(()) cast as xs:error?", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "xs-error-042", XPath: "() cast as xs:error?", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "xs-error-043", XPath: "xs:error(1) instance of xs:error", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "xs-error-044", XPath: "fn:error() instance of xs:error", AcceptError: true, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckTrue())}},
		{Name: "xs-error-047", XPath: "fn:error() treat as xs:error", ExpectError: true},
		{Name: "xs-error-048", XPath: "1 treat as xs:error", ExpectError: true},
		{Name: "xs-error-049", XPath: "() treat as xs:error?", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "xs-error-050", XPath: "1 cast as xs:error", ExpectError: true},
		{Name: "xs-error-051", XPath: "\"boo\" cast as xs:error", ExpectError: true},
		{Name: "xs-error-052", XPath: "1 castable as xs:error", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "xs-error-053", XPath: "1 castable as xs:error", Assertions: []qt3Assertion{qt3AssertFalse()}},
	})
}

func TestQT3_xs_float(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "xs-float-001", XPath: "fn:string(xs:float(\"-0\"))", Assertions: []qt3Assertion{qt3AssertEq("fn:string(\"-0\")")}},
		{Name: "xs-float-002", XPath: "1 div xs:float(\"-0\") ne 1 div xs:float(\"0\")", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-float-003", XPath: "exists(xs:float(\"+INF\"))", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-float-004", XPath: "exists(xs:float(\"+INF\"))", Skip: "requires XSD 1.0", ExpectError: true},
		{Name: "cbcl-float-001", XPath: "count(xs:float(()))", Assertions: []qt3Assertion{qt3AssertEq("0")}},
		{Name: "cbcl-float-002", XPath: "xs:float(xs:double('-INF')),xs:float(xs:double('INF'))", Assertions: []qt3Assertion{qt3AssertStringValue("-INF INF")}},
	})
}

func TestQT3_xs_hexBinary(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "cbcl-hexbinary-001", XPath: "count(xs:hexBinary(()))", Assertions: []qt3Assertion{qt3AssertStringValue("0")}},
	})
}

func TestQT3_xs_normalizedString(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "cbcl-normalizedstring-001", XPath: "xs:normalizedString(xs:normalizedString(\"test\"))", Assertions: []qt3Assertion{qt3AssertStringValue("test")}},
		{Name: "cbcl-normalizedstring-002b", XPath: "xs:normalizedString('\t')", Assertions: []qt3Assertion{qt3AssertStringValue(" ")}},
		{Name: "cbcl-normalizedstring-003", XPath: "xs:normalizedString(5)", Assertions: []qt3Assertion{qt3AssertStringValue("5")}},
		{Name: "cbcl-normalizedstring-004", XPath: "\"&#x9;\" castable as xs:normalizedString", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "cbcl-normalizedstring-005", XPath: "5 castable as xs:normalizedString", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "cbcl-normalizedstring-006", XPath: "xs:normalizedString(\"test\") castable as xs:normalizedString", Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}

func TestQT3_xs_numeric(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "xs-numeric-001", XPath: "3.14e0 instance of xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-002", XPath: "3.14 instance of xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-003", XPath: "3 instance of xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-004", XPath: "xs:float('93.7') instance of xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-005", XPath: "xs:nonNegativeInteger('93') instance of xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-006", XPath: `let $x := if (current-date() lt xs:date('2500-01-01')) then -3 else 'minus three'
        return abs($x treat as xs:numeric)`, Assertions: []qt3Assertion{qt3AssertEq("3")}},
		{Name: "xs-numeric-007", XPath: "xs:numeric('12') instance of xs:double", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-008", XPath: "xs:numeric('12.5') instance of xs:double", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-009", XPath: "xs:numeric('12.5e2') instance of xs:double", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-010", XPath: "xs:numeric('12.5f2') instance of xs:double", ExpectError: true},
		{Name: "xs-numeric-011", XPath: "'12.5' castable as xs:numeric", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-012", XPath: "'12.5.7' castable as xs:numeric", Assertions: []qt3Assertion{qt3AssertFalse()}},
		{Name: "xs-numeric-013", XPath: "17 cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("17"), qt3AssertType("xs:integer")}},
		{Name: "xs-numeric-014", XPath: "17.2 cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("17.2"), qt3AssertType("xs:decimal")}},
		{Name: "xs-numeric-015", XPath: "1e3 cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("1e3"), qt3AssertType("xs:double")}},
		{Name: "xs-numeric-016", XPath: "xs:float(1e3) cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("xs:float(1e3)"), qt3AssertType("xs:float")}},
		{Name: "xs-numeric-017", XPath: "xs:short(256) cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("256"), qt3AssertType("xs:short")}},
		{Name: "xs-numeric-018", XPath: "true() cast as xs:numeric", Assertions: []qt3Assertion{qt3AssertEq("1e0"), qt3AssertType("xs:double")}},
		{Name: "xs-numeric-019", XPath: "let $f := function($n as xs:numeric) as xs:numeric { $n+1 } return $f(255)", Assertions: []qt3Assertion{qt3AssertEq("256"), qt3AssertType("xs:integer")}},
		{Name: "xs-numeric-021", XPath: "/*/*:float instance of element(*, xs:numeric)", DocPath: "docs/atomic.xml", Namespaces: map[string]string{"atomic": "http://www.w3.org/XQueryTest"}, Skip: "requires XML Schema support", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "xs-numeric-022", XPath: "/*/*:decimal/@*:attr instance of attribute(*, xs:numeric)", DocPath: "docs/atomic.xml", Namespaces: map[string]string{"atomic": "http://www.w3.org/XQueryTest"}, Skip: "requires XML Schema support", Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}

func TestQT3_xs_token(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "cbcl-token-001", XPath: "xs:token(xs:token(\"test\"))", Assertions: []qt3Assertion{qt3AssertStringValue("test")}},
		{Name: "cbcl-token-002b", XPath: "string-length(xs:token('\t'))", Assertions: []qt3Assertion{qt3AssertStringValue("0")}},
		{Name: "cbcl-token-003", XPath: "xs:token(5)", Assertions: []qt3Assertion{qt3AssertStringValue("5")}},
		{Name: "cbcl-token-004", XPath: "\"&#x9;\" castable as xs:token", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "cbcl-token-005", XPath: "5 castable as xs:token", Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "cbcl-token-006", XPath: "xs:token(\"test\") castable as xs:token", Assertions: []qt3Assertion{qt3AssertTrue()}},
	})
}
