// Code generated by tools/qt3gen; DO NOT EDIT.

package xpath3_test

import "testing"

func TestQT3_method_json(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "Serialization-json-1", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        [ ]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-2", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        map { }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-3", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        ()`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-4", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        [(),map{"k":()},[()]]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-5", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        [true(), not(true())]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-6", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        1 eq 1`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-7", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        "abcd"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-8", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        ["a","b","c"]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-9", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        1234`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-10", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [12,12.34,xs:int("45"),xs:decimal("45.67"),xs:unsignedShort("89")]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-11", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        xs:float("-0")`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-12", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        xs:float("INF")`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-13", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [xs:double("-INF")]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-14", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        xs:double("NaN")`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-15", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { "a" : xs:float("NaN") }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-16", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        1e-5`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-17", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [-10000000 cast as xs:double]`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-json-18", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { "a" : xs:decimal(12678967.543233) cast as xs:float }`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-json-19", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        "abc"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-20", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [xs:QName("abc")]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-21", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { "a" : xs:gYearMonth("1995-05") }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-22", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        xs:hexBinary("0fb7")`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-23", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        1, 2`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-24", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [(1, 2)]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-25", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { "a" : (1, 2) }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-26", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [1],[2]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-27", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        <e/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-28", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        comment {" hello world "}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-29", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        array {
           text { "a" },
           processing-instruction {"a"} {"b"},
           comment { "a" },
           element {"a"} {"b"},
           document { element {"a"}{"b"} }
        }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-30", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        [attribute {"a"} {"b"}]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-31", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:normalization-form "NFC";
        
        "suc&#807;on"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-32", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:normalization-form "none";
        
        "suc&#807;on"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-33", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        "-&#x10330;-"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-34", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        
        ["abc","XabcX"]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-35", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        declare option output:normalization-form "NFC";
        
        "|z|"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-36", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        
        map { "|y|" : "y" }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-37", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        
        map { "w" : 1, "x" : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-38", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        
        xs:QName("abc")`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-39", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-character-map.xml";
        
        [123, "123", xs:gDay("---11")]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-40", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        codepoints-to-string((9,10,13,32))`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-41", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { """" : "\
"}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-42", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:encoding "US-ASCII";
        
        "&#x10330;"`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-json-43", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        "<"`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-44", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        text { "<" }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-45", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:allow-duplicate-names "yes";
        
        map { "one" : 1, xs:QName("one") : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-46", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:allow-duplicate-names "no";
        
        map { "one" : 1, xs:QName("one") : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-47", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        
        map { "on" || "e" : 1, xs:QName("one") : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-48", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:allow-duplicate-names "no";
        
        map { "a" : map { "a" : map { "a" : 1 } } }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-49", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:allow-duplicate-names "no";
        
        map { "1" : map { "1" : map { "1" : 1 }, 1 : 1 } }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-50", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:allow-duplicate-names "no";
        
        map { "a": 1, "2014-10-01" : 1, "b" : 1, xs:date("2014-10-01") : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-51", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:json-node-output-method "xml";
        
        <e>hi</e>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-52", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:json-node-output-method "text";
        
        <e>hi</e>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-53", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-node-serialization.xml";
        
        <e>hi</e>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-54", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-allow-duplicates.xml";
        
        map { "one" : 1, xs:QName("one") : 1 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-55", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:parameter-document "json/json-allow-duplicates.xml";
        [text { "&#xd;" }, "&#xd;"]`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-json-56", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        [(),(),<e><f>a</f></e>,()]`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-57", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "json";
        declare option output:encoding "US-ASCII";
                
        "&#x20ac;"`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-json-58", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-59", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

parse-json(unparsed-text('json/data001.json'))`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-60", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

parse-json(unparsed-text('json/data002.json'))`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-61", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

parse-json(unparsed-text('json/data003.json'))`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-62", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

parse-json(unparsed-text('json/data004.json'))`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-63", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

parse-json(unparsed-text('json/data005.json'))`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-64", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "xml-content": <simple>text-value</simple>,
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-65", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "xml-content": element simple { "text-value" },
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-66", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "xml-content": element simple { 1 + 1 },
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-67", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            element simple { 1 + 1 },
            map {
                "last": "Suciu",
                "first": "Dan"
           }
        ],
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-68", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        <node-key>strange</node-key> : element simple { 1 + 1 },
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-69", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "xml-content": <complex><simple>text-value</simple></complex>,
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-70", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";

map {
    "book": map {
        "title": "Data on the Web",
        "year": 2000,
        "author": [
            map {
                "last": "Abiteboul",
                "first": "Serge"
            },
            map {
                "last": "Buneman",
                "first": "Peter"
            },
            map {
                "last": "Suciu",
                "first": "Dan"
            }
        ],
        "xml-content": <complex><simple>text-value</simple></complex>,
        "publisher": "Morgan Kaufmann Publishers",
        "price": 39.95
    }
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-71", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
  "string-value": "a string",
  "numeric-value": 123.456,
  "node-value": element el1 { element el2 { "simple content" }},
  xs:integer("123456"): xs:integer("123456"),
  xs:date("2014-09-30"): "date-key",
  "array": [
    xs:integer("123456"), xs:date("2014-09-30"), xs:boolean("true"), xs:boolean("false")
  ]
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-72", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";
declare option output:allow-duplicate-names "yes";

map {
  "string-value": "a string",
  "numeric-value": 123.456,
  "node-value": element el1 { element el2 { "simple content" }},
  xs:integer("123456"): xs:integer("123456"),
  xs:date("2014-09-30"): "date-key",
  "2014-09-30": "string date key",
  "array": [
    xs:integer("123456"), xs:date("2014-09-30"), xs:boolean("true"), xs:boolean("false")
  ]
}`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-json-73", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";
declare option output:allow-duplicate-names "no";

map {
  "string-value": "a string",
  "numeric-value": 123.456,
  "node-value": element el1 { element el2 { "simple content" }},
  xs:integer("123456"): xs:integer("123456"),
  xs:date("2014-09-30"): "date-key",
  "2014-09-30": "string date key",
  "array": [
    xs:integer("123456"), xs:date("2014-09-30"), xs:boolean("true"), xs:boolean("false")
  ]
}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-json-74", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "json";
declare option output:indent  "no";
declare option output:media-type  "text/json";
declare option output:encoding  "UTF-8";
declare option output:json-node-output-method  "xml";

map {
  "string-value": "a string",
  "numeric-value": 123.456,
  "node-value": element el1 { element el2 { "simple content" }},
  xs:integer("123456"): xs:integer("123456"),
  xs:date("2014-09-30"): "date-key",
  "2014-09-30": "string date key",
  "array": [
    xs:integer("123456"), xs:date("2014-09-30"), xs:boolean("true"), xs:boolean("false")
  ]
}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
	})
}

func TestQT3_method_text(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "Serialization-text-1", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        attribute name {<anElement/>}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-2", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <e/>, attribute name {<anElement/>}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-3", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        attribute name {<anElement/>}, <e/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-4", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <e/>, attribute name {<anElement/>}, <e/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-5", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a>&#xD;&#x85;&#x2028;</a>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip())}},
		{Name: "Serialization-text-6", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a attr="&#xD;&#xA;&#x9;&#x85;&#x2028;"/>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip())}},
		{Name: "Serialization-text-7", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a>{codepoints-to-string(1 to 31)}</a>`, Skip: "requires XML 1.1", Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-7a", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a>{codepoints-to-string(1 to 31)}</a>`, ExpectError: true},
		{Name: "Serialization-text-8", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a attr="{codepoints-to-string(1 to 31)}"></a>`, Skip: "requires XML 1.1", Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-8a", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a attr="{codepoints-to-string(1 to 31)}"></a>`, ExpectError: true},
		{Name: "Serialization-text-9", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a attr="{codepoints-to-string(127 to 159)}"/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-10", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        <a>{codepoints-to-string(127 to 159)}</a>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-11", XPath: `declare option Q{http://www.w3.org/2010/xslt-xquery-serialization}method  "text";
        "a&#xD;aa&#xD;&#xA;a&#xD;&#xA;"`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-text-13", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        declare option output:item-separator "|";
        1 to 10`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-14", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        declare option output:item-separator "|";
        <a>{1,2,3}</a>,<b>{4,5,6}</b>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-15", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        declare option output:item-separator "|";
        document { 1 to 5 }`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-16", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        declare option output:item-separator "==";
        (1 to 4)!text{.}`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-17", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        <a>&lt;&amp;&gt;</a>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-text-18", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
        declare option output:method "text";
        <a>The <?quick brown?>fox<!--jumped--> down</a>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
	})
}

func TestQT3_method_xhtml(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "Serialization-xhtml-1", XPath: `declare boundary-space strip;
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";

<html xmlns="http://www.w3.org/1999/xhtml"><body><area/><base/><br/><col/><embed/><frame/><hr/><img/><input/><isindex/><link/><meta/><param/></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-1a", XPath: `declare boundary-space strip;
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";

<html><body><area/><base/><br/><col/><embed/><frame/><hr/><img/><input/><isindex/><link/><meta/><param/></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-2", XPath: `declare boundary-space strip;        
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";

<html><body><area/><base/><br/><col/><embed/><hr/><img/><input/><keygen/><link/><meta/><param/><source/><track/><wbr/></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-3", XPath: `declare boundary-space strip;        
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";

<html xmlns="http://www.w3.org/1999/xhtml"><body><area/><base/><br/><col/><embed/><frame/><hr/><img/><input/><isindex/><link/><meta/><param/></body></html>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-xhtml-4", XPath: `declare boundary-space strip;        
declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";

<html xmlns="http://www.w3.org/1999/xhtml"><body><area/><base/><br/><col/><embed
/><frame/><hr/><img/><input/><isindex/><link/><meta/><param/></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-18", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare namespace ex = "http://www.example.org";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";
declare option output:cdata-section-elements  "p em ex:isle1";

<html><body><p>YES<em>YES</em>YES<ex:isle1>YES<ex:isle2>NO</ex:isle2>YES</ex:isle1></p></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-19a", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare namespace ex = "http://www.example.org";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:cdata-section-elements  "p em ex:isle1";

<html><body><p>YES<em>YES</em>YES<ex:isle1>YES<ex:isle2>NO</ex:isle2>YES</ex:isle1></p></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-19b", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare namespace html = "http://www.w3.org/1999/xhtml";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";
declare option output:cdata-section-elements  "b html:em";

<html><body><p><b>YES</b><em>NO</em><html:b>NO</html:b><html:em>YES</html:em></p></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-19c", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare namespace html = "http://www.w3.org/1999/xhtml";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:cdata-section-elements  "b html:em";

<html><body><p><b>YES</b><em>NO</em><html:b>NO</html:b><html:em>YES</html:em></p></body></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-20", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";

<html/>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-xhtml-21", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";

<html/>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip())}},
		{Name: "Serialization-xhtml-22", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";

<html/>`, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckSkip(), qt3CheckSkip()), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-23", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";

<foo/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-24", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";

<foo/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-25", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";
declare option output:doctype-public  "-//W3C//DTD HTML 4.0//EN";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-26", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";
declare option output:doctype-system  "http://www.w3.org/TR/REC-html40/strict.dtd";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-27", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:doctype-public  "-//W3C//DTD HTML 4.0//EN";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-27a", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:doctype-public  "-//W3C//DTD HTML 4.0//EN";

<html xmlns="http://www.w3.org/1999/xhtml"/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-28", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:doctype-system  "about:legacy-compat";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-29", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "4.0";
declare option output:doctype-system  "http://www.w3.org/TR/REC-html40/strict.dtd";
declare option output:doctype-public  "-//W3C//DTD HTML 4.0//EN";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-30", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:html-version  "5.0";
declare option output:doctype-system  "http://www.w3.org/TR/REC-html40/strict.dtd";
declare option output:doctype-public  "-//W3C//DTD HTML 4.0//EN";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-31", XPath: "()", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "Serialization-xhtml-32", XPath: "()", Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "Serialization-xhtml-33", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "4.0";

<html xmlns="http://www.w3.org/1999/xhtml"><head/></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-34", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "4.0";

<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html;version='3.0'"/></head></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-35", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "4.0";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-36", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html><head/></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-36a", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html xmlns="http://www.w3.org/1999/xhtml"><head/></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-37", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html><head><meta http-equiv="Content-Type" content="text/html;version='3.0'"/></head></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-37a", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html><head><meta http-equiv="Content-Type" content="text/html;version='3.0'"/></head></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-38", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "yes";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html/>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
		{Name: "Serialization-xhtml-39", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "no";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "4.0";

<html><head/></html>`, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "Serialization-xhtml-40", XPath: `declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method  "xhtml";
declare option output:indent  "no";
declare option output:include-content-type  "no";
declare option output:media-type  "text/html";
declare option output:encoding  "UTF-8";
declare option output:html-version  "5.0";

<html><head/></html>`, Assertions: []qt3Assertion{qt3AssertSkip(), qt3AssertSkip()}},
	})
}
