// Code generated by tools/qt3gen; DO NOT EDIT.

package xpath3_test

import "testing"

func TestQT3_math_acos(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-acos-001", XPath: "math:acos(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-acos-002", XPath: "math:acos(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-acos-003", XPath: "math:acos(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-acos-004", XPath: "math:acos(1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-acos-005", XPath: "math:acos(-1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("3.141592653589793e0")}},
		{Name: "math-acos-006", XPath: "math:acos(2.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-acos-007", XPath: "math:acos(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-acos-008", XPath: "math:acos(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-acos-009", XPath: "math:acos(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_asin(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-asin-001", XPath: "math:asin(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-asin-002", XPath: "math:asin(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-asin-003", XPath: "math:asin(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-asin-004", XPath: "math:asin(1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.5707963267948966e0")}},
		{Name: "math-asin-005", XPath: "math:asin(-1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-1.5707963267948966e0")}},
		{Name: "math-asin-006", XPath: "math:asin(2.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-asin-007", XPath: "math:asin(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-asin-08", XPath: "math:asin(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-asin-09", XPath: "math:asin(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_atan(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-atan-001", XPath: "math:atan(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-atan-002", XPath: "math:atan(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-atan-003", XPath: "math:atan(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-atan-004", XPath: "math:atan(1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.7853981633974483e0")}},
		{Name: "math-atan-005", XPath: "math:atan(-1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.7853981633974483e0")}},
		{Name: "math-atan-006", XPath: "math:atan(-1.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.7853981633974483e0")}},
		{Name: "math-atan-007", XPath: "math:atan(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-atan-008", XPath: "math:atan(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.5707963267948966e0")}},
		{Name: "math-atan-009", XPath: "math:atan(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-1.5707963267948966e0")}},
	})
}

func TestQT3_math_atan2(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-atan2-001", XPath: "math:atan2(+0.0e0, 0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-atan2-002", XPath: "math:atan2(-0.0e0, 0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-atan2-003", XPath: "math:atan2(+0.0e0, -0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-004", XPath: "math:atan2(-0.0e0, -0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-005", XPath: "math:atan2(-1, -0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-006", XPath: "math:atan2(+1, 0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-007", XPath: "math:atan2(-0.0e0, -1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-008", XPath: "math:atan2(+0.0e0, -1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-atan2-009", XPath: "math:atan2(-0.0e0, +1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-atan2-010", XPath: "math:atan2(+0.0e0, +1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("+0.0e0")}},
	})
}

func TestQT3_math_cos(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-cos-001", XPath: "math:cos(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-cos-002", XPath: "math:cos(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-cos-003", XPath: "math:cos(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-cos-004", XPath: "math:cos(math:pi() div 2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-cos-005", XPath: "math:cos(-math:pi() div 2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-cos-006", XPath: "math:cos(math:pi())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-1.0e0")}},
		{Name: "math-cos-007", XPath: "math:cos(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-cos-008", XPath: "math:cos(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-cos-009", XPath: "math:cos(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_exp(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-exp-001", XPath: "math:exp(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-exp-002", XPath: "math:exp(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-exp-003", XPath: "math:exp(1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-exp-004", XPath: "math:exp(2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("7.38905609893065e0")}},
		{Name: "math-exp-005", XPath: "math:exp(-1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.36787944117144233e0")}},
		{Name: "math-exp-006", XPath: "math:exp(math:pi())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("23.140692632779267e0")}},
		{Name: "math-exp-007", XPath: "math:exp(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-exp-008", XPath: "math:exp(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-exp-009", XPath: "math:exp(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
	})
}

func TestQT3_math_exp10(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-exp10-001", XPath: "math:exp10(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-exp10-002", XPath: "math:exp10(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-exp10-003", XPath: "math:exp10(1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e1")}},
		{Name: "math-exp10-004", XPath: "math:exp10(0.5)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AnyOf(qt3CheckEq("3.1622776601683795"), qt3CheckEq("3.162277660168379"))}},
		{Name: "math-exp10-005", XPath: "math:exp10(-1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e-1")}},
		{Name: "math-exp10-006", XPath: "math:exp10(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-exp10-007", XPath: "math:exp10(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-exp10-008", XPath: "math:exp10(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
	})
}

func TestQT3_math_log(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-log-001", XPath: "math:log(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-log-002", XPath: "math:log(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('-INF')")}},
		{Name: "math-log-003", XPath: "math:log(math:exp(1))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-log-004", XPath: "math:log(1.0e-3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-6.907755278982137e0")}},
		{Name: "math-log-005", XPath: "math:log(2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.6931471805599453e0")}},
		{Name: "math-log-006", XPath: "math:log(-1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-log-007", XPath: "math:log(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-log-008", XPath: "math:log(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-log-009", XPath: "math:log(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_log10(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-log10-001", XPath: "math:log10(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-log10-002", XPath: "math:log10(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('-INF')")}},
		{Name: "math-log10-003", XPath: "math:log10(1.0e3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("3.0e0")}},
		{Name: "math-log10-004", XPath: "math:log10(1.0e-3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-3.0e0")}},
		{Name: "math-log10-005", XPath: "math:log10(2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.3010299956639812e0")}},
		{Name: "math-log10-006", XPath: "math:log10(-1)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-log10-007", XPath: "math:log10(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-log10-008", XPath: "math:log10(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-log10-009", XPath: "math:log10(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_pi(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-pi-001", XPath: "2*math:pi()", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("6.283185307179586e0")}},
		{Name: "math-pi-002", XPath: "60 * (math:pi() div 180)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-pi-003", XPath: "math:pi()", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("3.141592653589793e0")}},
		{Name: "math-pi-004", XPath: "math:pi#0()", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("3.141592653589793e0")}},
		{Name: "math-pi-005", XPath: "function-lookup(xs:QName('math:pi'), 0)()", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("3.141592653589793e0")}},
	})
}

func TestQT3_math_pow(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-pow-001", XPath: "math:pow((), 93.7)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-pow-002", XPath: "math:pow(2, 3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("8.0e0")}},
		{Name: "math-pow-003", XPath: "math:pow(-2, 3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-8.0e0")}},
		{Name: "math-pow-004", XPath: "math:pow(-2, -3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.125e0")}},
		{Name: "math-pow-005", XPath: "math:pow(2, 0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-006", XPath: "math:pow(0, 0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-007", XPath: "math:pow(xs:double('INF'), 0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-008", XPath: "math:pow(xs:double('NaN'), 0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-009", XPath: "math:pow(-math:pi(), 0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-010", XPath: "math:pow(0e0, 3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-011", XPath: "math:pow(0e0, 4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-012", XPath: "math:pow(-0e0, 3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-pow-013", XPath: "math:pow(0, 4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-014", XPath: "math:pow(0e0, -3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-015", XPath: "math:pow(0e0, -4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-016", XPath: "math:pow(-0e0, -3)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('-INF')")}},
		{Name: "math-pow-017", XPath: "math:pow(0, -4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-018", XPath: "math:pow(16, 0.5e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("4.0e0")}},
		{Name: "math-pow-019", XPath: "math:pow(16, 0.25e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("2.0e0")}},
		{Name: "math-pow-020", XPath: "math:pow(0e0, -3.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-021", XPath: "math:pow(-0e0, -3.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('-INF')")}},
		{Name: "math-pow-022", XPath: "math:pow(0e0, -3.1e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-023", XPath: "math:pow(-0e0, -3.1e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-pow-024", XPath: "math:pow(0e0, 3.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-025", XPath: "math:pow(-0e0, 3.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-pow-026", XPath: "math:pow(0e0, 3.1e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-027", XPath: "math:pow(-0e0, 3.1e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-pow-028", XPath: "math:pow(-1, xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-029", XPath: "math:pow(-1, xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-030", XPath: "math:pow(1, xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-031", XPath: "math:pow(1, xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-032", XPath: "math:pow(1, xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-pow-033", XPath: "math:pow(-2.5e0, 2.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("6.25e0")}},
		{Name: "math-pow-034", XPath: "math:pow(-2.5e0, 2.00000001e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_sin(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-sin-001", XPath: "math:sin(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-sin-002", XPath: "math:sin(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-sin-003", XPath: "math:sin(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-sin-004", XPath: "math:sin(math:pi() div 2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e0")}},
		{Name: "math-sin-005", XPath: "math:sin(-math:pi() div 2)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-1.0e0")}},
		{Name: "math-sin-006", XPath: "math:sin(math:pi()) lt 1e-15", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertTrue()}},
		{Name: "math-sin-007", XPath: "math:sin(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-sin-008", XPath: "math:sin(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-sin-009", XPath: "math:sin(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_sqrt(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-sqrt-001", XPath: "math:sqrt(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-sqrt-002", XPath: "math:sqrt(0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-sqrt-003", XPath: "math:sqrt(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-sqrt-004", XPath: "math:sqrt(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-sqrt-005", XPath: "math:sqrt(1.0e6)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.0e3")}},
		{Name: "math-sqrt-006", XPath: "math:sqrt(2.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("1.4142135623730951e0")}},
		{Name: "math-sqrt-007", XPath: "math:sqrt(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-sqrt-008", XPath: "math:sqrt(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("xs:double('INF')")}},
		{Name: "math-sqrt-010", XPath: "math:sqrt(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}

func TestQT3_math_tan(t *testing.T) {
	t.Parallel()
	qt3RunTests(t, []qt3Test{
		{Name: "math-tan-001", XPath: "math:tan(())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEmpty()}},
		{Name: "math-tan-002", XPath: "math:tan(0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("0.0e0")}},
		{Name: "math-tan-003", XPath: "math:tan(-0.0e0)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertEq("-0.0e0")}},
		{Name: "math-tan-004", XPath: "math:tan(math:pi() div 4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-tan-005", XPath: "math:tan(-math:pi() div 4)", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-tan-006", XPath: "math:tan(math:pi() div 4) - 1", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-tan-007", XPath: "math:tan(-math:pi() div 4) + 1", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-tan-008", XPath: "math:tan(math:pi())", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertSkip()}},
		{Name: "math-tan-009", XPath: "math:tan(xs:double('NaN'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-tan-010", XPath: "math:tan(xs:double('INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
		{Name: "math-tan-011", XPath: "math:tan(xs:double('-INF'))", Namespaces: map[string]string{"math": "http://www.w3.org/2005/xpath-functions/math"}, Assertions: []qt3Assertion{qt3AssertStringValue("NaN")}},
	})
}
