package helium_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lestrrat-go/helium"
	"github.com/stretchr/testify/require"
)

// TestLibxml2Compat runs helium against libxml2's own test suite data.
//
// Test inputs and expected outputs live in testdata/libxml2-compat/.
// They are committed to the repo and generated by testdata/libxml2/generate.sh
// from a libxml2 clone (see testdata/libxml2/fetch.sh).
//
// Each test file has a corresponding .expected file containing the
// expected xmllint output (parse + serialize roundtrip).
//
// Environment variable HELIUM_LIBXML2_TEST_FILES can be set to test
// only specific files:
//
//	HELIUM_LIBXML2_TEST_FILES=att1,comment.xml go test -run TestLibxml2Compat
func TestLibxml2Compat(t *testing.T) {
	dir := "testdata/libxml2-compat"

	if _, err := os.Stat(dir); err != nil {
		t.Skipf("testdata/libxml2-compat not found; run testdata/libxml2/generate.sh first")
	}

	// Files known to fail — add entries here with a reason as you triage.
	skipped := map[string]string{}

	only := map[string]struct{}{}
	if v := os.Getenv("HELIUM_LIBXML2_TEST_FILES"); v != "" {
		for _, f := range strings.Split(v, ",") {
			only[strings.TrimSpace(f)] = struct{}{}
		}
	}

	files, err := os.ReadDir(dir)
	require.NoError(t, err, "os.ReadDir should succeed")

	for _, fi := range files {
		if fi.IsDir() {
			continue
		}

		name := fi.Name()

		// Skip .expected, .err, .sax2.expected, .sax2.err files
		if strings.HasSuffix(name, ".expected") || strings.HasSuffix(name, ".err") ||
			strings.HasSuffix(name, ".sax2.expected") || strings.HasSuffix(name, ".sax2.err") {
			continue
		}

		if len(only) > 0 {
			if _, ok := only[name]; !ok {
				continue
			}
		}

		if reason, ok := skipped[name]; ok {
			t.Logf("Skipping %s: %s", name, reason)
			continue
		}

		// Check that a corresponding .expected file exists
		expectedPath := filepath.Join(dir, name+".expected")
		if _, err := os.Stat(expectedPath); err != nil {
			continue
		}

		t.Run(name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("panic: %v", r)
				}
			}()

			input, err := os.ReadFile(filepath.Join(dir, name))
			require.NoError(t, err, "reading input file")

			expected, err := os.ReadFile(expectedPath)
			require.NoError(t, err, "reading expected file")

			p := helium.NewParser()
			doc, err := p.Parse(t.Context(), input)
			if err != nil {
				t.Fatalf("parsing %s: %v", name, err)
			}

			var buf bytes.Buffer
			d := helium.NewWriter()
			if err := d.WriteDoc(&buf, doc); err != nil {
				t.Fatalf("dumping %s: %v", name, err)
			}

			actual := buf.String()

			if string(expected) != actual {
				errPath := filepath.Join(dir, name+".err")
				_ = os.WriteFile(errPath, []byte(actual), 0600)
				t.Logf("Actual output saved to %s", errPath)
			}
			require.Equal(t, string(expected), actual, "output should match libxml2 expected result")
		})
	}
}
