// This file is auto-generated by internal/cmd/gennodes/main.go. DO NOT EDIT

package helium

type Attribute struct {
	atype       AttributeType
	defaultAttr bool
	doc         *Document
	firstChild  Node
	lastChild   Node
	name        string
	next        Node
	ns          *Namespace
	parent      Node
	prev        Node
}

func (*Attribute) Type() ElementType {
	return AttributeNode
}

func (n *Attribute) IsDefault() bool {
	return n.defaultAttr
}

func (n *Attribute) SetDefault(v bool) {
	n.defaultAttr = v
}

func (n *Attribute) OwnerDocument() *Document {
	return n.doc
}

func (n *Attribute) SetOwnerDocument(v *Document) {
	n.doc = v
}

func (n *Attribute) FirstChild() Node {
	return n.firstChild
}

func (n *Attribute) setFirstChild(v Node) {
	n.firstChild = v
}

func (n *Attribute) LastChild() Node {
	return n.lastChild
}

func (n *Attribute) setLastChild(v Node) {
	n.lastChild = v
}

func (n *Attribute) LocalName() string {
	return n.name
}

func (n *Attribute) NextSibling() Node {
	return n.next
}

func (n *Attribute) SetNextSibling(v Node) {
	n.next = v
}

func (n *Attribute) Parent() Node {
	return n.parent
}

func (n *Attribute) SetParent(v Node) {
	n.parent = v
}

func (n *Attribute) PrevSibling() Node {
	return n.prev
}

func (n *Attribute) SetPrevSibling(v Node) {
	n.prev = v
}

func (n *Attribute) AddChild(c Node) error {
	return addChild(n, c)
}

func (n *Attribute) AddContent(b []byte) error {
	return addContent(n, b)
}

func (n *Attribute) AddSibling(c Node) error {
	return addSibling(n, c)
}

func (n *Attribute) Content() []byte {
	return getContent(n)
}

func (n *Attribute) Replace(v Node) {
	replaceNode(n, v)
}
