// This file is auto-generated by internal/cmd/gennodes/main.go. DO NOT EDIT

package helium

type EntityRef struct {
	content    []byte
	doc        *Document
	firstChild Node
	lastChild  Node
	name       string
	next       Node
	ns         *Namespace
	nsDefs     []*Namespace
	parent     Node
	prev       Node
	private    interface{}
	properties *Attribute
}

func (*EntityRef) Type() ElementType {
	return EntityRefNode
}

func (n *EntityRef) Content() []byte {
	return n.content
}

func (n *EntityRef) OwnerDocument() *Document {
	return n.doc
}

func (n *EntityRef) SetOwnerDocument(v *Document) {
	n.doc = v
}

func (n *EntityRef) FirstChild() Node {
	return n.firstChild
}

func (n *EntityRef) setFirstChild(v Node) {
	n.firstChild = v
}

func (n *EntityRef) LastChild() Node {
	return n.lastChild
}

func (n *EntityRef) setLastChild(v Node) {
	n.lastChild = v
}

func (n *EntityRef) LocalName() string {
	return n.name
}

func (n *EntityRef) NextSibling() Node {
	return n.next
}

func (n *EntityRef) SetNextSibling(v Node) {
	n.next = v
}

func (n *EntityRef) Parent() Node {
	return n.parent
}

func (n *EntityRef) SetParent(v Node) {
	n.parent = v
}

func (n *EntityRef) PrevSibling() Node {
	return n.prev
}

func (n *EntityRef) SetPrevSibling(v Node) {
	n.prev = v
}

func (n *EntityRef) AddChild(c Node) error {
	return addChild(n, c)
}

func (n *EntityRef) AddContent(b []byte) error {
	return addContent(n, b)
}

func (n *EntityRef) AddSibling(c Node) error {
	return addSibling(n, c)
}

func (n *EntityRef) Replace(v Node) {
	replaceNode(n, v)
}
