// This file is auto-generated by internal/cmd/gennodes/main.go. DO NOT EDIT

package helium

type Namespace struct {
	content    []byte
	context    *Document
	doc        *Document
	firstChild Node
	href       string
	lastChild  Node
	name       string
	next       Node
	ns         *Namespace
	nsDefs     []*Namespace
	parent     Node
	prefix     string
	prev       Node
	private    interface{}
	properties *Attribute
}

func (*Namespace) Type() ElementType {
	return NamespaceNode
}

func (n *Namespace) Content() []byte {
	return n.content
}

func (n *Namespace) OwnerDocument() *Document {
	return n.doc
}

func (n *Namespace) SetOwnerDocument(v *Document) {
	n.doc = v
}

func (n *Namespace) FirstChild() Node {
	return n.firstChild
}

func (n *Namespace) setFirstChild(v Node) {
	n.firstChild = v
}

func (n *Namespace) URI() string {
	return n.href
}

func (n *Namespace) LastChild() Node {
	return n.lastChild
}

func (n *Namespace) setLastChild(v Node) {
	n.lastChild = v
}

func (n *Namespace) LocalName() string {
	return n.name
}

func (n *Namespace) NextSibling() Node {
	return n.next
}

func (n *Namespace) SetNextSibling(v Node) {
	n.next = v
}

func (n *Namespace) Parent() Node {
	return n.parent
}

func (n *Namespace) SetParent(v Node) {
	n.parent = v
}

func (n *Namespace) Prefix() string {
	return n.prefix
}

func (n *Namespace) PrevSibling() Node {
	return n.prev
}

func (n *Namespace) SetPrevSibling(v Node) {
	n.prev = v
}

func (n *Namespace) AddChild(c Node) error {
	return addChild(n, c)
}

func (n *Namespace) AddContent(b []byte) error {
	return addContent(n, b)
}

func (n *Namespace) AddSibling(c Node) error {
	return addSibling(n, c)
}

func (n *Namespace) Replace(v Node) {
	replaceNode(n, v)
}
