// This file is auto-generated by internal/cmd/gennodes/main.go. DO NOT EDIT

package helium

type Text struct {
	content    []byte
	doc        *Document
	firstChild Node
	lastChild  Node
	name       string
	next       Node
	ns         *Namespace
	nsDefs     []*Namespace
	parent     Node
	prev       Node
	private    interface{}
	properties *Attribute
}

func (*Text) Type() ElementType {
	return TextNode
}

func (n *Text) Content() []byte {
	return n.content
}

func (n *Text) OwnerDocument() *Document {
	return n.doc
}

func (n *Text) SetOwnerDocument(v *Document) {
	n.doc = v
}

func (n *Text) FirstChild() Node {
	return n.firstChild
}

func (n *Text) setFirstChild(v Node) {
	n.firstChild = v
}

func (n *Text) LastChild() Node {
	return n.lastChild
}

func (n *Text) setLastChild(v Node) {
	n.lastChild = v
}

func (n *Text) LocalName() string {
	return n.name
}

func (n *Text) NextSibling() Node {
	return n.next
}

func (n *Text) SetNextSibling(v Node) {
	n.next = v
}

func (n *Text) Parent() Node {
	return n.parent
}

func (n *Text) SetParent(v Node) {
	n.parent = v
}

func (n *Text) PrevSibling() Node {
	return n.prev
}

func (n *Text) SetPrevSibling(v Node) {
	n.prev = v
}

func (n *Text) AddSibling(c Node) error {
	return addSibling(n, c)
}

func (n *Text) Replace(v Node) {
	replaceNode(n, v)
}
