#!perl
use strict;

# This script generates the SAX2 handler interfaces, func adapters,
# and the callback-based SAX2 struct.

open my $fh, '<', "types.go" or die;

while (my $ln = <$fh>) {
    if ($ln =~ /^\/\/ SAX functions/) {
        last;
    }
}

my %handler_returns;
my %handler_args;
my @handler_funcs;
while (my $ln = <$fh>) {
    if ($ln =~ /^type (.+)Func func\(([^)]+)\) (\([^\)]+\)|.+)$/) {
        push @handler_funcs, $1;
        $handler_args{$1} = $2;
        $handler_returns{$1} = $3;
    }
}

sub bare_args {
    my ($args) = @_;
    return join ", ", map {
        my @parts = split /\s+/, $_;
        if ($parts[1] =~ /^\.\.\./) {
            "$parts[0]..."
        } else {
            $parts[0]
        }
    } split /\s*,\s*/, $args;
}

sub lcfirst_name {
    my ($name) = @_;
    return lcfirst($name);
}

open my $out, '>', 'sax2.go' or die;

my $klass = "SAX2";
print $out <<EOM;
// WARNING: This file is generated by $0
package sax

import (
\t"context"
\t"errors"

\t"github.com/lestrrat-go/helium/enum"
)

// ErrHandlerUnspecified is returned when there is no Handler
// registered for that particular event callback. This is not
// a fatal error per se, and can be ignored if the implementation
// chooses to do so.
var ErrHandlerUnspecified = errors.New("handler unspecified")

// SAX2Handler is an interface for anything that can satisfy
// helium's expected SAX2 API.
// (libxml2: xmlSAXHandler / xmlSAXHandlerPtr)
type SAX2Handler interface {
EOM

foreach my $func (@handler_funcs) {
    my $args = $handler_args{$func};
    my $ret  = $handler_returns{$func};
    print $out "\t$func($args) $ret\n";
}

print $out <<EOM;
}

EOM

# Generate individual handler interfaces and Handle methods on XXXFunc
foreach my $func (@handler_funcs) {
    my $args = $handler_args{$func};
    my $ret  = $handler_returns{$func};
    my $ba = bare_args($args);

    print $out <<EOM;
// $func is the interface for the $func handler.
type $func interface {
\tHandle($args) $ret
}

func (f ${func}Func) Handle($args) $ret {
\treturn f($ba)
}

EOM
}

# Generate SAX2 struct with unexported fields
print $out <<EOM;
// $klass is a callback-based SAX2 handler.
// (libxml2: xmlSAXHandler with function pointers)
type $klass struct {
EOM

foreach my $func (@handler_funcs) {
    my $field = lcfirst_name("on${func}");
    print $out "\t${field} ${func}\n";
}

print $out <<EOM;
}

// New creates a new instance of $klass. All callbacks are
// uninitialized.
func New() *${klass} {
\treturn &${klass}{}
}

EOM

# Generate setter methods
foreach my $func (@handler_funcs) {
    my $field = lcfirst_name("on${func}");
    print $out <<EOM
// SetOn${func} sets the handler for the ${func} event.
func (s *$klass) SetOn${func}(h ${func}) {
\ts.${field} = h
}

EOM
}

# Generate delegation methods
foreach my $func (@handler_funcs) {
    my $args = $handler_args{$func};
    my $ret  = $handler_returns{$func};
    my $no_handler_ret  =
        join ", ",
            map { $_ eq "error" ? "ErrHandlerUnspecified" : $_ eq "bool" ? "false" : "nil" }
            split /\s*,\s*/, $ret =~ s{\(([^\)]+)\)}{$1}r;
    my $ba = bare_args($args);
    my $field = lcfirst_name("on${func}");
    print $out <<EOM
func (s *$klass) $func($args) $ret {
\tif h := s.${field}; h != nil {
\t\treturn h.Handle($ba)
\t}
\treturn $no_handler_ret
}

EOM
}
