<?xml version="1.0" encoding="UTF-8"?>
<!-- Imported page-chrome module: named templates for the header and footer,
     plus a param the main module can override. Loaded via xsl:import, so the
     compile-time URIResolver must resolve "layout.xsl" against the base URI. -->
<xsl:stylesheet version="3.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs">

  <xsl:param name="tagline" as="xs:string" select="'Fresh picks, updated daily.'"/>

  <xsl:template name="page-header">
    <xsl:param name="title" as="xs:string" required="yes"/>
    <header>
      <h1><xsl:value-of select="$title"/></h1>
      <p class="tagline"><xsl:value-of select="$tagline"/></p>
    </header>
  </xsl:template>

  <xsl:template name="page-footer">
    <footer>
      <p>Generated by helium xslt3.</p>
    </footer>
  </xsl:template>

</xsl:stylesheet>
