package xsd

const (
	elemAll            = "all"
	elemAnnotation     = "annotation"
	elemAny            = "any"
	elemAnyAttribute   = "anyAttribute"
	elemAppinfo        = "appinfo"
	elemAttribute      = "attribute"
	elemAttributeGroup = "attributeGroup"
	elemChoice         = "choice"
	elemComplexContent = "complexContent"
	elemComplexType    = "complexType"
	elemDocumentation  = "documentation"
	elemElement        = "element"
	elemExtension      = "extension"
	elemField          = "field"
	elemGroup          = "group"
	elemImport         = "import"
	elemInclude        = "include"
	elemKey            = "key"
	elemKeyRef         = "keyref"
	elemList           = "list"
	elemRedefine       = "redefine"
	elemRestriction    = "restriction"
	elemSchema         = "schema"
	elemSelector       = "selector"
	elemSequence       = "sequence"
	elemSimpleContent  = "simpleContent"
	elemSimpleType     = "simpleType"
	elemUnion          = "union"
	elemUnique         = "unique"
)

const (
	attrAbstract             = "abstract"
	attrAttributeFormDefault = "attributeFormDefault"
	attrBase                 = "base"
	attrBlock                = "block"
	attrBlockDefault         = "blockDefault"
	attrDefault              = "default"
	attrElementFormDefault   = "elementFormDefault"
	attrFinal                = "final"
	attrFinalDefault         = "finalDefault"
	attrFixed                = "fixed"
	attrForm                 = "form"
	attrItemType             = "itemType"
	attrMaxOccurs            = "maxOccurs"
	attrMemberTypes          = "memberTypes"
	attrMinOccurs            = "minOccurs"
	attrName                 = "name"
	attrNamespace            = "namespace"
	attrNillable             = "nillable"
	attrNil                  = "nil"
	attrProcessContents      = "processContents"
	attrRefer                = "refer"
	attrRef                  = "ref"
	attrSchemaLocation       = "schemaLocation"
	attrSource               = "source"
	attrSubstitutionGroup    = "substitutionGroup"
	attrTargetNamespace      = "targetNamespace"
	attrType                 = "type"
	attrUse                  = "use"
	attrXPath                = "xpath"
)

const (
	attrValExtension    = "extension"
	attrValLax          = "lax"
	attrValList         = "list"
	attrValOptional     = "optional"
	attrValProhibited   = "prohibited"
	attrValRequired     = "required"
	attrValRestriction  = "restriction"
	attrValSkip         = "skip"
	attrValSubstitution = "substitution"
	attrValUnbounded    = "unbounded"
	attrValUnion        = "union"
)
