package xsd_test

import "strings"

// xstsSkipIDs lists the W3C XML Schema Test Suite (XSTS) case IDs that the xsd
// package does not yet pass under XSD 1.1 mode. Each ID is a known conformance
// gap (not a regression); delete an ID as the underlying feature lands. The
// list is grouped and sorted by testSet (the case ID minus its last path
// segment) so a whole feature area can be cleared at once. Baseline captured
// 2026-06-28.
//
// This is the ONLY place W3C XSTS cases are skipped; never skip a non-W3C xsd
// test here.
var xstsSkipIDs = []string{
	// ibmMeta/allGroup.testSet (3)
	"ibmMeta/allGroup.testSet/s3_3_6ii01",
	"ibmMeta/allGroup.testSet/s3_3_6v01",
	"ibmMeta/allGroup.testSet/s3_3_6v05",

	// ibmMeta/assert.testSet (16)
	"ibmMeta/assert.testSet/assert_002",
	"ibmMeta/assert.testSet/assert_011",
	"ibmMeta/assert.testSet/assert_013",
	"ibmMeta/assert.testSet/assert_015",
	"ibmMeta/assert.testSet/assert_016",
	"ibmMeta/assert.testSet/assert_018",
	"ibmMeta/assert.testSet/assert_021",
	"ibmMeta/assert.testSet/assert_023",
	"ibmMeta/assert.testSet/assert_025",
	"ibmMeta/assert.testSet/assert_026",
	"ibmMeta/assert.testSet/assert_029",
	"ibmMeta/assert.testSet/assert_030",
	"ibmMeta/assert.testSet/assert_031",
	"ibmMeta/assert.testSet/assert_032",
	"ibmMeta/assert.testSet/assert_034",
	"ibmMeta/assert.testSet/assert_035",

	// ibmMeta/assertion.testSet (14)
	"ibmMeta/assertion.testSet/d4_3_15ii08",
	"ibmMeta/assertion.testSet/d4_3_15ii14",
	"ibmMeta/assertion.testSet/d4_3_15ii15",
	"ibmMeta/assertion.testSet/d4_3_15ii18",
	"ibmMeta/assertion.testSet/d4_3_15ii19",
	"ibmMeta/assertion.testSet/d4_3_15ii20",
	"ibmMeta/assertion.testSet/d4_3_15ii22",
	"ibmMeta/assertion.testSet/d4_3_15ii24",
	"ibmMeta/assertion.testSet/d4_3_15si04",
	"ibmMeta/assertion.testSet/d4_3_15v02",
	"ibmMeta/assertion.testSet/d4_3_15v11",
	"ibmMeta/assertion.testSet/d4_3_15v13",
	"ibmMeta/assertion.testSet/d4_3_15v21",
	"ibmMeta/assertion.testSet/d4_3_15v23",

	// ibmMeta/conditionalInclusion.testSet (2)
	"ibmMeta/conditionalInclusion.testSet/s4_2_2ii01",
	"ibmMeta/conditionalInclusion.testSet/s4_2_2v01",

	// ibmMeta/constraintsOnAttribute.testSet (11)
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3ii01",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3ii02",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3ii04",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3ii05",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3si01",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3si02",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3si04",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3si07",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3si08",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3v01",
	"ibmMeta/constraintsOnAttribute.testSet/s3_2_3v04",

	// ibmMeta/dateTimeStamp.testSet (9)
	"ibmMeta/dateTimeStamp.testSet/d3_4_28ii01",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28si11",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28si14",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v01",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v02",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v06",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v07",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v08",
	"ibmMeta/dateTimeStamp.testSet/d3_4_28v09",

	// ibmMeta/dayTimeDuration.testSet (9)
	"ibmMeta/dayTimeDuration.testSet/d3_4_27ii03",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27ii04",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27ii05",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27ii07",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27si10",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27v01",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27v02",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27v04",
	"ibmMeta/dayTimeDuration.testSet/d3_4_27v05",

	// ibmMeta/defaultAttributesApply.testSet (7)
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4ii06",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4ii07",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4si01",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4si02",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4v01",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4v03",
	"ibmMeta/defaultAttributesApply.testSet/s3_4_2_4v13",

	// ibmMeta/edcWildcard.testSet (1)
	"ibmMeta/edcWildcard.testSet/s3_8_6v01",

	// ibmMeta/explicitTimezone.testSet (6)
	"ibmMeta/explicitTimezone.testSet/d4_3_16ii02",
	"ibmMeta/explicitTimezone.testSet/d4_3_16ii03",
	"ibmMeta/explicitTimezone.testSet/d4_3_16si01",
	"ibmMeta/explicitTimezone.testSet/d4_3_16si02",
	"ibmMeta/explicitTimezone.testSet/d4_3_16si03",
	"ibmMeta/explicitTimezone.testSet/d4_3_16si04",

	// ibmMeta/idIDREF.testSet (25)
	"ibmMeta/idIDREF.testSet/s3_3_4ii02",
	"ibmMeta/idIDREF.testSet/s3_3_4ii04",
	"ibmMeta/idIDREF.testSet/s3_3_4ii06",
	"ibmMeta/idIDREF.testSet/s3_3_4ii07",
	"ibmMeta/idIDREF.testSet/s3_3_4ii10",
	"ibmMeta/idIDREF.testSet/s3_3_4ii11",
	"ibmMeta/idIDREF.testSet/s3_3_4ii12",
	"ibmMeta/idIDREF.testSet/s3_3_4ii13",
	"ibmMeta/idIDREF.testSet/s3_3_4ii14",
	"ibmMeta/idIDREF.testSet/s3_3_4ii15",
	"ibmMeta/idIDREF.testSet/s3_3_4ii16",
	"ibmMeta/idIDREF.testSet/s3_3_4ii17",
	"ibmMeta/idIDREF.testSet/s3_3_4ii18",
	"ibmMeta/idIDREF.testSet/s3_3_4ii19",
	"ibmMeta/idIDREF.testSet/s3_3_4ii20",
	"ibmMeta/idIDREF.testSet/s3_3_4ii21",
	"ibmMeta/idIDREF.testSet/s3_3_4ii22",
	"ibmMeta/idIDREF.testSet/s3_3_4ii23",
	"ibmMeta/idIDREF.testSet/s3_3_4ii24",
	"ibmMeta/idIDREF.testSet/s3_3_4ii25",
	"ibmMeta/idIDREF.testSet/s3_3_4ii26",
	"ibmMeta/idIDREF.testSet/s3_3_4ii27",
	"ibmMeta/idIDREF.testSet/s3_3_4si07",
	"ibmMeta/idIDREF.testSet/s3_3_4si08",
	"ibmMeta/idIDREF.testSet/s3_3_4v02",

	// ibmMeta/identityConstraint.testSet (1)
	"ibmMeta/identityConstraint.testSet/s2_2_4si01",

	// ibmMeta/openContent.testSet (13)
	"ibmMeta/openContent.testSet/s3_4_1ii04",
	"ibmMeta/openContent.testSet/s3_4_1si02",
	"ibmMeta/openContent.testSet/s3_4_1si06",
	"ibmMeta/openContent.testSet/s3_4_1si08",
	"ibmMeta/openContent.testSet/s3_4_1si09",
	"ibmMeta/openContent.testSet/s3_4_1v01",
	"ibmMeta/openContent.testSet/s3_4_1v02",
	"ibmMeta/openContent.testSet/s3_4_1v04",
	"ibmMeta/openContent.testSet/s3_4_1v05",
	"ibmMeta/openContent.testSet/s3_4_1v06",
	"ibmMeta/openContent.testSet/s3_4_1v07",
	"ibmMeta/openContent.testSet/s3_4_1v08",
	"ibmMeta/openContent.testSet/s3_4_1v10",

	// ibmMeta/restrictionOfComplexTypes.testSet (3)
	"ibmMeta/restrictionOfComplexTypes.testSet/s3_4_6ii01",
	"ibmMeta/restrictionOfComplexTypes.testSet/s3_4_6v01",
	"ibmMeta/restrictionOfComplexTypes.testSet/s3_4_6v05",

	// ibmMeta/substitutionGroup.testSet (3)
	"ibmMeta/substitutionGroup.testSet/s2_2_2si02",
	"ibmMeta/substitutionGroup.testSet/s2_2_2v01",
	"ibmMeta/substitutionGroup.testSet/s2_2_2v02",

	// ibmMeta/targetNamespace.testSet (1)
	"ibmMeta/targetNamespace.testSet/targetNamespace_005",

	// ibmMeta/typeAlternatives.testSet (8)
	"ibmMeta/typeAlternatives.testSet/s3_12ii06",
	"ibmMeta/typeAlternatives.testSet/s3_12si03",
	"ibmMeta/typeAlternatives.testSet/s3_12v01",
	"ibmMeta/typeAlternatives.testSet/s3_12v02",
	"ibmMeta/typeAlternatives.testSet/s3_12v03",
	"ibmMeta/typeAlternatives.testSet/s3_12v04",
	"ibmMeta/typeAlternatives.testSet/s3_12v08",
	"ibmMeta/typeAlternatives.testSet/s3_12v09",

	// ibmMeta/typeAlternativesMixed.testSet (3)
	"ibmMeta/typeAlternativesMixed.testSet/typeAlternatives_003",
	"ibmMeta/typeAlternativesMixed.testSet/typeAlternatives_004",
	"ibmMeta/typeAlternativesMixed.testSet/typeAlternatives_006",

	// ibmMeta/union.testSet (1)
	"ibmMeta/union.testSet/s3_16_2v05",

	// ibmMeta/unitsLength.testSet (1)
	"ibmMeta/unitsLength.testSet/d3_1si01",

	// ibmMeta/vc.testSet (6)
	"ibmMeta/vc.testSet/vc_001",
	"ibmMeta/vc.testSet/vc_003",
	"ibmMeta/vc.testSet/vc_005",
	"ibmMeta/vc.testSet/vc_007",
	"ibmMeta/vc.testSet/vc_008",
	"ibmMeta/vc.testSet/vc_009",

	// ibmMeta/wildcard.testSet (2)
	"ibmMeta/wildcard.testSet/s3_10_1v05",
	"ibmMeta/wildcard.testSet/s3_10_1v06",

	// ibmMeta/xml11Support.testSet (1)
	"ibmMeta/xml11Support.testSet/d3_4_6v07",

	// ibmMeta/yearMonthDuration.testSet (9)
	"ibmMeta/yearMonthDuration.testSet/d3_4_26ii03",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26ii04",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26ii05",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26ii07",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26si10",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26v01",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26v02",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26v04",
	"ibmMeta/yearMonthDuration.testSet/d3_4_26v05",

	// oracleMeta/Zone.testSet (4)
	"oracleMeta/Zone.testSet/zone403",
	"oracleMeta/Zone.testSet/zone404",
	"oracleMeta/Zone.testSet/zone408",
	"oracleMeta/Zone.testSet/zone409",

	// saxonMeta/All.testSet (29)
	"saxonMeta/All.testSet/all001",
	"saxonMeta/All.testSet/all002",
	"saxonMeta/All.testSet/all003",
	"saxonMeta/All.testSet/all004",
	"saxonMeta/All.testSet/all005",
	"saxonMeta/All.testSet/all006",
	"saxonMeta/All.testSet/all007",
	"saxonMeta/All.testSet/all201",
	"saxonMeta/All.testSet/all206",
	"saxonMeta/All.testSet/all211",
	"saxonMeta/All.testSet/all216",
	"saxonMeta/All.testSet/all217",
	"saxonMeta/All.testSet/all221",
	"saxonMeta/All.testSet/all222",
	"saxonMeta/All.testSet/all225",
	"saxonMeta/All.testSet/all226",
	"saxonMeta/All.testSet/all230",
	"saxonMeta/All.testSet/all231",
	"saxonMeta/All.testSet/all232",
	"saxonMeta/All.testSet/all234",
	"saxonMeta/All.testSet/all237",
	"saxonMeta/All.testSet/all242",
	"saxonMeta/All.testSet/all301",
	"saxonMeta/All.testSet/all304",
	"saxonMeta/All.testSet/all306",
	"saxonMeta/All.testSet/all307",
	"saxonMeta/All.testSet/all310",
	"saxonMeta/All.testSet/all311",
	"saxonMeta/All.testSet/all314",

	// saxonMeta/Assert.testSet (24)
	"saxonMeta/Assert.testSet/assert-simple001",
	"saxonMeta/Assert.testSet/assert-simple003",
	"saxonMeta/Assert.testSet/assert-simple004",
	"saxonMeta/Assert.testSet/assert-simple005",
	"saxonMeta/Assert.testSet/assert-simple006",
	"saxonMeta/Assert.testSet/assert-simple007",
	"saxonMeta/Assert.testSet/assert-simple008",
	"saxonMeta/Assert.testSet/assert-simple009",
	"saxonMeta/Assert.testSet/assert-simple010",
	"saxonMeta/Assert.testSet/assert006",
	"saxonMeta/Assert.testSet/assert008",
	"saxonMeta/Assert.testSet/assert008a",
	"saxonMeta/Assert.testSet/assert010",
	"saxonMeta/Assert.testSet/assert011",
	"saxonMeta/Assert.testSet/assert013",
	"saxonMeta/Assert.testSet/assert014",
	"saxonMeta/Assert.testSet/assert015",
	"saxonMeta/Assert.testSet/assert018",
	"saxonMeta/Assert.testSet/assert019",
	"saxonMeta/Assert.testSet/assert020",
	"saxonMeta/Assert.testSet/assert021",
	"saxonMeta/Assert.testSet/assert022",
	"saxonMeta/Assert.testSet/assert023",
	"saxonMeta/Assert.testSet/assert024",

	// saxonMeta/CTA.testSet (24)
	"saxonMeta/CTA.testSet/cta0001",
	"saxonMeta/CTA.testSet/cta0002",
	"saxonMeta/CTA.testSet/cta0003",
	"saxonMeta/CTA.testSet/cta0004",
	"saxonMeta/CTA.testSet/cta0005",
	"saxonMeta/CTA.testSet/cta0006",
	"saxonMeta/CTA.testSet/cta0007",
	"saxonMeta/CTA.testSet/cta0008",
	"saxonMeta/CTA.testSet/cta0009",
	"saxonMeta/CTA.testSet/cta0010",
	"saxonMeta/CTA.testSet/cta0011",
	"saxonMeta/CTA.testSet/cta0012",
	"saxonMeta/CTA.testSet/cta0013",
	"saxonMeta/CTA.testSet/cta0021",
	"saxonMeta/CTA.testSet/cta0040",
	"saxonMeta/CTA.testSet/cta0041",
	"saxonMeta/CTA.testSet/cta0042",
	"saxonMeta/CTA.testSet/cta0043",
	"saxonMeta/CTA.testSet/cta0044",
	"saxonMeta/CTA.testSet/cta9001err",
	"saxonMeta/CTA.testSet/cta9002err",
	"saxonMeta/CTA.testSet/cta9003err",
	"saxonMeta/CTA.testSet/cta9009err",
	"saxonMeta/CTA.testSet/cta9010err",

	// saxonMeta/Complex.testSet (4)
	"saxonMeta/Complex.testSet/complex001",
	"saxonMeta/Complex.testSet/complex002",
	"saxonMeta/Complex.testSet/complex009",
	"saxonMeta/Complex.testSet/complex010",

	// saxonMeta/Id.testSet (29)
	"saxonMeta/Id.testSet/id001",
	"saxonMeta/Id.testSet/id002",
	"saxonMeta/Id.testSet/id003",
	"saxonMeta/Id.testSet/id004",
	"saxonMeta/Id.testSet/id005",
	"saxonMeta/Id.testSet/id006",
	"saxonMeta/Id.testSet/id007",
	"saxonMeta/Id.testSet/id008",
	"saxonMeta/Id.testSet/id010",
	"saxonMeta/Id.testSet/id011",
	"saxonMeta/Id.testSet/id012",
	"saxonMeta/Id.testSet/id013",
	"saxonMeta/Id.testSet/id014",
	"saxonMeta/Id.testSet/id015",
	"saxonMeta/Id.testSet/id016",
	"saxonMeta/Id.testSet/id017",
	"saxonMeta/Id.testSet/id018",
	"saxonMeta/Id.testSet/id019",
	"saxonMeta/Id.testSet/id020",
	"saxonMeta/Id.testSet/id021",
	"saxonMeta/Id.testSet/id040",
	"saxonMeta/Id.testSet/id041",
	"saxonMeta/Id.testSet/id042",
	"saxonMeta/Id.testSet/id043",
	"saxonMeta/Id.testSet/id044",
	"saxonMeta/Id.testSet/id050",
	"saxonMeta/Id.testSet/id051",
	"saxonMeta/Id.testSet/id052",
	"saxonMeta/Id.testSet/id053",

	// saxonMeta/Open.testSet (36)
	"saxonMeta/Open.testSet/open002",
	"saxonMeta/Open.testSet/open006",
	"saxonMeta/Open.testSet/open008",
	"saxonMeta/Open.testSet/open009",
	"saxonMeta/Open.testSet/open011",
	"saxonMeta/Open.testSet/open012",
	"saxonMeta/Open.testSet/open013",
	"saxonMeta/Open.testSet/open016.bad",
	"saxonMeta/Open.testSet/open017",
	"saxonMeta/Open.testSet/open018",
	"saxonMeta/Open.testSet/open019",
	"saxonMeta/Open.testSet/open021",
	"saxonMeta/Open.testSet/open025",
	"saxonMeta/Open.testSet/open027",
	"saxonMeta/Open.testSet/open030",
	"saxonMeta/Open.testSet/open031",
	"saxonMeta/Open.testSet/open033",
	"saxonMeta/Open.testSet/open035",
	"saxonMeta/Open.testSet/open036",
	"saxonMeta/Open.testSet/open037",
	"saxonMeta/Open.testSet/open038",
	"saxonMeta/Open.testSet/open039",
	"saxonMeta/Open.testSet/open040",
	"saxonMeta/Open.testSet/open041",
	"saxonMeta/Open.testSet/open042",
	"saxonMeta/Open.testSet/open043",
	"saxonMeta/Open.testSet/open044",
	"saxonMeta/Open.testSet/open045",
	"saxonMeta/Open.testSet/open046",
	"saxonMeta/Open.testSet/open047",
	"saxonMeta/Open.testSet/open048",
	"saxonMeta/Open.testSet/open201",
	"saxonMeta/Open.testSet/open202",
	"saxonMeta/Open.testSet/open203",
	"saxonMeta/Open.testSet/open204",
	"saxonMeta/Open.testSet/open205",

	// saxonMeta/Override.testSet (27)
	"saxonMeta/Override.testSet/over001",
	"saxonMeta/Override.testSet/over002",
	"saxonMeta/Override.testSet/over003",
	"saxonMeta/Override.testSet/over004",
	"saxonMeta/Override.testSet/over005",
	"saxonMeta/Override.testSet/over006",
	"saxonMeta/Override.testSet/over007",
	"saxonMeta/Override.testSet/over008",
	"saxonMeta/Override.testSet/over009",
	"saxonMeta/Override.testSet/over010",
	"saxonMeta/Override.testSet/over011",
	"saxonMeta/Override.testSet/over012",
	"saxonMeta/Override.testSet/over014",
	"saxonMeta/Override.testSet/over015",
	"saxonMeta/Override.testSet/over016",
	"saxonMeta/Override.testSet/over017",
	"saxonMeta/Override.testSet/over018",
	"saxonMeta/Override.testSet/over019",
	"saxonMeta/Override.testSet/over020",
	"saxonMeta/Override.testSet/over021",
	"saxonMeta/Override.testSet/over022",
	"saxonMeta/Override.testSet/over023",
	"saxonMeta/Override.testSet/over024",
	"saxonMeta/Override.testSet/over026",
	"saxonMeta/Override.testSet/over028",
	"saxonMeta/Override.testSet/over029",
	"saxonMeta/Override.testSet/over030",

	// saxonMeta/Simple.testSet (33)
	"saxonMeta/Simple.testSet/simple005",
	"saxonMeta/Simple.testSet/simple010",
	"saxonMeta/Simple.testSet/simple012",
	"saxonMeta/Simple.testSet/simple013",
	"saxonMeta/Simple.testSet/simple016",
	"saxonMeta/Simple.testSet/simple041",
	"saxonMeta/Simple.testSet/simple042",
	"saxonMeta/Simple.testSet/simple050",
	"saxonMeta/Simple.testSet/simple051",
	"saxonMeta/Simple.testSet/simple052",
	"saxonMeta/Simple.testSet/simple053",
	"saxonMeta/Simple.testSet/simple060",
	"saxonMeta/Simple.testSet/simple061",
	"saxonMeta/Simple.testSet/simple062",
	"saxonMeta/Simple.testSet/simple063",
	"saxonMeta/Simple.testSet/simple064",
	"saxonMeta/Simple.testSet/simple065",
	"saxonMeta/Simple.testSet/simple066",
	"saxonMeta/Simple.testSet/simple067",
	"saxonMeta/Simple.testSet/simple068",
	"saxonMeta/Simple.testSet/simple071",
	"saxonMeta/Simple.testSet/simple072",
	"saxonMeta/Simple.testSet/simple073",
	"saxonMeta/Simple.testSet/simple074",
	"saxonMeta/Simple.testSet/simple075",
	"saxonMeta/Simple.testSet/simple076",
	"saxonMeta/Simple.testSet/simple077",
	"saxonMeta/Simple.testSet/simple078",
	"saxonMeta/Simple.testSet/simple079",
	"saxonMeta/Simple.testSet/simple080",
	"saxonMeta/Simple.testSet/simple083",
	"saxonMeta/Simple.testSet/simple084",
	"saxonMeta/Simple.testSet/simple095",

	// saxonMeta/Subsgroup.testSet (4)
	"saxonMeta/Subsgroup.testSet/subsgroup001",
	"saxonMeta/Subsgroup.testSet/subsgroup002",
	"saxonMeta/Subsgroup.testSet/subsgroup003",
	"saxonMeta/Subsgroup.testSet/subsgroup901",

	// saxonMeta/TargetNS.testSet (4)
	"saxonMeta/TargetNS.testSet/target001",
	"saxonMeta/TargetNS.testSet/target002",
	"saxonMeta/TargetNS.testSet/target003",
	"saxonMeta/TargetNS.testSet/target004",

	// saxonMeta/VC.testSet (11)
	"saxonMeta/VC.testSet/vc005",
	"saxonMeta/VC.testSet/vc006",
	"saxonMeta/VC.testSet/vc007",
	"saxonMeta/VC.testSet/vc011",
	"saxonMeta/VC.testSet/vc012",
	"saxonMeta/VC.testSet/vc021",
	"saxonMeta/VC.testSet/vc022",
	"saxonMeta/VC.testSet/vc901",
	"saxonMeta/VC.testSet/vc903",
	"saxonMeta/VC.testSet/vc904",
	"saxonMeta/VC.testSet/vc905",

	// saxonMeta/Wild.testSet (79)
	"saxonMeta/Wild.testSet/wild001",
	"saxonMeta/Wild.testSet/wild002",
	"saxonMeta/Wild.testSet/wild003",
	"saxonMeta/Wild.testSet/wild004",
	"saxonMeta/Wild.testSet/wild005",
	"saxonMeta/Wild.testSet/wild006",
	"saxonMeta/Wild.testSet/wild007",
	"saxonMeta/Wild.testSet/wild008",
	"saxonMeta/Wild.testSet/wild009",
	"saxonMeta/Wild.testSet/wild010",
	"saxonMeta/Wild.testSet/wild011",
	"saxonMeta/Wild.testSet/wild012",
	"saxonMeta/Wild.testSet/wild014",
	"saxonMeta/Wild.testSet/wild015",
	"saxonMeta/Wild.testSet/wild016",
	"saxonMeta/Wild.testSet/wild017",
	"saxonMeta/Wild.testSet/wild018",
	"saxonMeta/Wild.testSet/wild020",
	"saxonMeta/Wild.testSet/wild021",
	"saxonMeta/Wild.testSet/wild022",
	"saxonMeta/Wild.testSet/wild023",
	"saxonMeta/Wild.testSet/wild024",
	"saxonMeta/Wild.testSet/wild025",
	"saxonMeta/Wild.testSet/wild026",
	"saxonMeta/Wild.testSet/wild027",
	"saxonMeta/Wild.testSet/wild028",
	"saxonMeta/Wild.testSet/wild029",
	"saxonMeta/Wild.testSet/wild030",
	"saxonMeta/Wild.testSet/wild031",
	"saxonMeta/Wild.testSet/wild032",
	"saxonMeta/Wild.testSet/wild033",
	"saxonMeta/Wild.testSet/wild034",
	"saxonMeta/Wild.testSet/wild035",
	"saxonMeta/Wild.testSet/wild036",
	"saxonMeta/Wild.testSet/wild037",
	"saxonMeta/Wild.testSet/wild038",
	"saxonMeta/Wild.testSet/wild039",
	"saxonMeta/Wild.testSet/wild041",
	"saxonMeta/Wild.testSet/wild043",
	"saxonMeta/Wild.testSet/wild044",
	"saxonMeta/Wild.testSet/wild045",
	"saxonMeta/Wild.testSet/wild046",
	"saxonMeta/Wild.testSet/wild047",
	"saxonMeta/Wild.testSet/wild049",
	"saxonMeta/Wild.testSet/wild050",
	"saxonMeta/Wild.testSet/wild052",
	"saxonMeta/Wild.testSet/wild053",
	"saxonMeta/Wild.testSet/wild054",
	"saxonMeta/Wild.testSet/wild055",
	"saxonMeta/Wild.testSet/wild056",
	"saxonMeta/Wild.testSet/wild057",
	"saxonMeta/Wild.testSet/wild058",
	"saxonMeta/Wild.testSet/wild059",
	"saxonMeta/Wild.testSet/wild060",
	"saxonMeta/Wild.testSet/wild061",
	"saxonMeta/Wild.testSet/wild062",
	"saxonMeta/Wild.testSet/wild063",
	"saxonMeta/Wild.testSet/wild064",
	"saxonMeta/Wild.testSet/wild065",
	"saxonMeta/Wild.testSet/wild067",
	"saxonMeta/Wild.testSet/wild068",
	"saxonMeta/Wild.testSet/wild069",
	"saxonMeta/Wild.testSet/wild070",
	"saxonMeta/Wild.testSet/wild071",
	"saxonMeta/Wild.testSet/wild072",
	"saxonMeta/Wild.testSet/wild073",
	"saxonMeta/Wild.testSet/wild074",
	"saxonMeta/Wild.testSet/wild075",
	"saxonMeta/Wild.testSet/wild076",
	"saxonMeta/Wild.testSet/wild078",
	"saxonMeta/Wild.testSet/wild079",
	"saxonMeta/Wild.testSet/wild081",
	"saxonMeta/Wild.testSet/wild082",
	"saxonMeta/Wild.testSet/wild083",
	"saxonMeta/Wild.testSet/wild084",
	"saxonMeta/Wild.testSet/wild101",
	"saxonMeta/Wild.testSet/wild102",
	"saxonMeta/Wild.testSet/wild103",
	"saxonMeta/Wild.testSet/wild104",

	// saxonMeta/Zone.testSet (11)
	"saxonMeta/Zone.testSet/zone001",
	"saxonMeta/Zone.testSet/zone002",
	"saxonMeta/Zone.testSet/zone004",
	"saxonMeta/Zone.testSet/zone005",
	"saxonMeta/Zone.testSet/zone006",
	"saxonMeta/Zone.testSet/zone007",
	"saxonMeta/Zone.testSet/zone008",
	"saxonMeta/Zone.testSet/zone102",
	"saxonMeta/Zone.testSet/zone202",
	"saxonMeta/Zone.testSet/zone303",
	"saxonMeta/Zone.testSet/zone304",

	// wgMeta/IRI.testSet (1)
	"wgMeta/IRI.testSet/iri-001",

	// wgMeta/substitution-groups.testSet (3)
	"wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-1",
	"wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-2",
	"wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-3",
}

// xstsSkip maps each skipped case ID to its skip reason. The reason is derived
// from the testSet so the per-ID list above stays the single source of truth.
var xstsSkip = func() map[string]string {
	m := make(map[string]string, len(xstsSkipIDs))
	for _, id := range xstsSkipIDs {
		ts := id[:strings.LastIndex(id, "/")]
		m[id] = "XSD 1.1 conformance gap (baseline 2026-06-28): " + ts
	}
	return m
}()
