// Code generated by tools/xstsgen; DO NOT EDIT.

package xsd_test

var xstsOracleCases = []xstsCase{
	{
		ID:          "oracleMeta/Zone.testSet/zone401",
		SchemaRel:   "oracleData/Zone/zone401.xsd",
		SchemaValid: true,
		Files: map[string]string{
			"oracleData/Zone/zone401.n1.xml": `<doc>0000-09-19T13:00:00.000+02:00</doc>
`,
			"oracleData/Zone/zone401.n2.xml": `<doc>0000-09-19T24:00:00.001</doc>
`,
			"oracleData/Zone/zone401.v1.xml": `<doc>0000-09-19T24:00:00Z</doc>
`,
			"oracleData/Zone/zone401.v2.xml": `<doc>0000-09-20T12:00:00.000+00:00</doc>
`,
			"oracleData/Zone/zone401.v3.xml": `<doc>0000-09-20T13:00:00.000+01:00</doc>
`,
			"oracleData/Zone/zone401.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- equality testing (enumeration) for dateTime values, use YEAR as ZERO -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">
         <xs:explicitTimezone value="required"/>
         <xs:enumeration value="0000-09-20T00:00:00Z"/>
         <xs:enumeration value="0000-09-20T12:00:00Z"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
		Instances: []xstsInstance{
			{Name: "zone401.v1.xml", Rel: "oracleData/Zone/zone401.v1.xml", Valid: true},
			{Name: "zone401.v2.xml", Rel: "oracleData/Zone/zone401.v2.xml", Valid: true},
			{Name: "zone401.v3.xml", Rel: "oracleData/Zone/zone401.v3.xml", Valid: true},
			{Name: "zone401.n1.xml", Rel: "oracleData/Zone/zone401.n1.xml", Valid: false},
			{Name: "zone401.n2.xml", Rel: "oracleData/Zone/zone401.n2.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone402",
		SchemaRel:   "oracleData/Zone/zone402.xsd",
		SchemaValid: true,
		Files: map[string]string{
			"oracleData/Zone/zone402.n1.xml": `<doc>0000-01-01T13:00:00</doc>
`,
			"oracleData/Zone/zone402.n2.xml": `<doc>0000-02-29T13:00:00</doc>
`,
			"oracleData/Zone/zone402.v1.xml": `<doc>0000-01-01T11:00:00</doc>
`,
			"oracleData/Zone/zone402.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test year zero allowed for facet maxInclusive for datatype xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">
         <xs:maxInclusive value="0000-01-01T12:00:00"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
		Instances: []xstsInstance{
			{Name: "zone402.n1.xml", Rel: "oracleData/Zone/zone402.n1.xml", Valid: false},
			{Name: "zone402.n2.xml", Rel: "oracleData/Zone/zone402.n2.xml", Valid: false},
			{Name: "zone402.v1.xml", Rel: "oracleData/Zone/zone402.v1.xml", Valid: true},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone403",
		SchemaRel:   "oracleData/Zone/zone403.xsd",
		SchemaValid: true,
		Files: map[string]string{
			"oracleData/Zone/zone403.n1.xml": `<doc>2010-09-19T13:00:00.000</doc>
`,
			"oracleData/Zone/zone403.v1.xml": `<doc>2010-09-19T13:00:00.000+02:00</doc>
`,
			"oracleData/Zone/zone403.v2.xml": `<doc>2010-09-19T24:00:00Z</doc>
`,
			"oracleData/Zone/zone403.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test new timezone facet explicitTimezone, value="required" for datatype xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">     
         <xs:explicitTimezone value="required"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
		Instances: []xstsInstance{
			{Name: "zone403.v1.xml", Rel: "oracleData/Zone/zone403.v1.xml", Valid: true},
			{Name: "zone403.v2.xml", Rel: "oracleData/Zone/zone403.v2.xml", Valid: true},
			{Name: "zone403.n1.xml", Rel: "oracleData/Zone/zone403.n1.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone404",
		SchemaRel:   "oracleData/Zone/zone404.xsd",
		SchemaValid: true,
		Files: map[string]string{
			"oracleData/Zone/zone404.n1.xml": `<doc>2010-09-19T13:00:00.000+02:00</doc>
`,
			"oracleData/Zone/zone404.n2.xml": `<doc>2010-09-19T24:00:00Z</doc>
`,
			"oracleData/Zone/zone404.v1.xml": `<doc>2010-09-19T13:00:00.000</doc>
`,
			"oracleData/Zone/zone404.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test new timezone facet explicitTimezone, value="prohibited" for datatype xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">     
         <xs:explicitTimezone value="prohibited"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
		Instances: []xstsInstance{
			{Name: "zone404.v1.xml", Rel: "oracleData/Zone/zone404.v1.xml", Valid: true},
			{Name: "zone404.n1.xml", Rel: "oracleData/Zone/zone404.n1.xml", Valid: false},
			{Name: "zone404.n2.xml", Rel: "oracleData/Zone/zone404.n2.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone405",
		SchemaRel:   "oracleData/Zone/zone405.xsd",
		SchemaValid: true,
		Files: map[string]string{
			"oracleData/Zone/zone405.v1.xml": `<doc>2010-09-19T13:00:00.000</doc>
`,
			"oracleData/Zone/zone405.v2.xml": `<doc>2010-09-19T13:00:00.000+02:00</doc>
`,
			"oracleData/Zone/zone405.v3.xml": `<doc>2010-09-19T24:00:00Z</doc>
`,
			"oracleData/Zone/zone405.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test new timezone facet explicitTimezone, value="optional" for datatype xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">     
         <xs:explicitTimezone value="optional"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
		Instances: []xstsInstance{
			{Name: "zone405.v1.xml", Rel: "oracleData/Zone/zone405.v1.xml", Valid: true},
			{Name: "zone405.v2.xml", Rel: "oracleData/Zone/zone405.v2.xml", Valid: true},
			{Name: "zone405.v3.xml", Rel: "oracleData/Zone/zone405.v3.xml", Valid: true},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone406",
		SchemaRel:   "oracleData/Zone/zone406.bad.xsd",
		SchemaValid: false,
		Files: map[string]string{
			"oracleData/Zone/zone406.bad.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test day value must be no more than 30 if month is one of 4, 6, 9, or 11 for xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">
         <xs:maxInclusive value="2010-04-31T12:00:00"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone407",
		SchemaRel:   "oracleData/Zone/zone407.bad.xsd",
		SchemaValid: false,
		Files: map[string]string{
			"oracleData/Zone/zone407.bad.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test day value must be no more than 28 if month is 2 and Year is not divisible 4 in xs:dateTime -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="doc">
    <xs:simpleType>
       <xs:restriction base="xs:dateTime">
         <xs:maxInclusive value="2010-02-29T12:00:00"/>
       </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

`,
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone408",
		SchemaRel:   "oracleData/Zone/zone408.bad.xsd",
		SchemaValid: false,
		Files: map[string]string{
			"oracleData/Zone/zone408.bad.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test explicitTimezone facet: cannot derive "required" from "prohibited" -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="doc" type="timeStampProhibited"/>
  
    <xs:simpleType name="timeStampProhibited">
       <xs:restriction base="xs:time">     
         <xs:explicitTimezone value="prohibited"/>
       </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="timeStampRequired">
       <xs:restriction base="timeStampProhibited">     
         <xs:explicitTimezone value="required"/>
       </xs:restriction>
    </xs:simpleType>    
      
</xs:schema>
`,
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone409",
		SchemaRel:   "oracleData/Zone/zone409.bad.xsd",
		SchemaValid: false,
		Files: map[string]string{
			"oracleData/Zone/zone409.bad.xsd": `<?xml version="1.0" encoding="UTF-8"?>
<!-- Test explicitTimezone facet: cannot derive "prohibited" from "required" -->
<!-- requires XSD 1.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:element name="doc" type="timeStampRequired"/>
  
    <xs:simpleType name="timeStampRequired">
       <xs:restriction base="xs:time">     
         <xs:explicitTimezone value="required"/>
       </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="timeStampProhibited">
       <xs:restriction base="timeStampRequired">     
         <xs:explicitTimezone value="prohibited"/>
       </xs:restriction>
    </xs:simpleType>    
      
</xs:schema>
`,
		},
	},
}
