package lexicon

// XSLT element local name constants. These mirror the elem* constants in
// xslt3/stylesheet.go but are exported for use across packages.
const (
	XSLTElementAccumulator             = "accumulator"
	XSLTElementAccumulatorRule         = "accumulator-rule"
	XSLTElementAnalyzeString           = "analyze-string"
	XSLTElementApplyImports            = "apply-imports"
	XSLTElementApplyTemplates          = "apply-templates"
	XSLTElementAssert                  = "assert"
	XSLTElementAttribute               = "attribute"
	XSLTElementAttributeSet            = "attribute-set"
	XSLTElementBreak                   = "break"
	XSLTElementCallTemplate            = "call-template"
	XSLTElementCatch                   = "catch"
	XSLTElementCharacterMap            = "character-map"
	XSLTElementChoose                  = "choose"
	XSLTElementComment                 = "comment"
	XSLTElementContextItem             = "context-item"
	XSLTElementCopy                    = "copy"
	XSLTElementCopyOf                  = "copy-of"
	XSLTElementDecimalFormat           = "decimal-format"
	XSLTElementDocument                = "document"
	XSLTElementElement                 = "element"
	XSLTElementEvaluate                = "evaluate"
	XSLTElementExpose                  = "expose"
	XSLTElementFallback                = "fallback"
	XSLTElementForEach                 = "for-each"
	XSLTElementForEachGroup            = "for-each-group"
	XSLTElementFork                    = "fork"
	XSLTElementFunction                = "function"
	XSLTElementGlobalContextItem       = "global-context-item"
	XSLTElementIf                      = "if"
	XSLTElementImport                  = "import"
	XSLTElementImportSchema            = "import-schema"
	XSLTElementInclude                 = "include"
	XSLTElementIterate                 = "iterate"
	XSLTElementKey                     = "key"
	XSLTElementMap                     = "map"
	XSLTElementMapEntry                = "map-entry"
	XSLTElementMatchingSubstring       = "matching-substring"
	XSLTElementMerge                   = "merge"
	XSLTElementMergeAction             = "merge-action"
	XSLTElementMergeKey                = "merge-key"
	XSLTElementMergeSource             = "merge-source"
	XSLTElementMessage                 = "message"
	XSLTElementMode                    = "mode"
	XSLTElementNamespace               = "namespace"
	XSLTElementNamespaceAlias          = "namespace-alias"
	XSLTElementNextIteration           = "next-iteration"
	XSLTElementNextMatch               = "next-match"
	XSLTElementNonMatchingSubstring    = "non-matching-substring"
	XSLTElementNumber                  = "number"
	XSLTElementOnCompletion            = "on-completion"
	XSLTElementOnEmpty                 = "on-empty"
	XSLTElementOnNonEmpty              = "on-non-empty"
	XSLTElementOtherwise               = "otherwise"
	XSLTElementOutput                  = "output"
	XSLTElementOutputCharacter         = "output-character"
	XSLTElementParam                   = "param"
	XSLTElementPerformSort             = "perform-sort"
	XSLTElementProcessingInstruction   = "processing-instruction"
	XSLTElementPreserveSpace           = "preserve-space"
	XSLTElementResultDocument          = "result-document"
	XSLTElementSchema                  = "schema"
	XSLTElementSequence                = "sequence"
	XSLTElementSort                    = "sort"
	XSLTElementSourceDocument          = "source-document"
	XSLTElementStripSpace              = "strip-space"
	XSLTElementTemplate                = "template"
	XSLTElementText                    = "text"
	XSLTElementTry                     = "try"
	XSLTElementUsePackage              = "use-package"
	XSLTElementValueOf                 = "value-of"
	XSLTElementVariable                = "variable"
	XSLTElementWhen                    = "when"
	XSLTElementWherePopulated          = "where-populated"
	XSLTElementWithParam               = "with-param"

	// Additional elements from xsltElementVersion map in functions.go
	// that are not in the elem* constants.
	XSLTElementAccept    = "accept"
	XSLTElementArray     = "array"
	XSLTElementOverride  = "override"
	XSLTElementPackage   = "package"
	XSLTElementStylesheet = "stylesheet"
	XSLTElementTransform  = "transform"
)
