name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go_version: ["1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go_version }}

      - name: Download dependencies
        run: go mod download

      - name: Tidy dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run tests with debug tags
        run: |
          go test -v -race -tags debug ./...

      - name: Build helium-lint command
        run: |
          go build -v ./cmd/helium-lint
          rm helium-lint

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes detected:"
            git status --porcelain
            exit 1
          fi
